/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1bc87d9c91847a6f215496c203268482a08e6f70
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.jira.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.kestra.plugin.jira.client.invoker.ApiClient;
/**
 * Metadata for an item in an attachment archive.
 */
@JsonPropertyOrder({
  AttachmentArchiveItemReadable.JSON_PROPERTY_INDEX,
  AttachmentArchiveItemReadable.JSON_PROPERTY_LABEL,
  AttachmentArchiveItemReadable.JSON_PROPERTY_MEDIA_TYPE,
  AttachmentArchiveItemReadable.JSON_PROPERTY_PATH,
  AttachmentArchiveItemReadable.JSON_PROPERTY_SIZE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class AttachmentArchiveItemReadable {
  public static final String JSON_PROPERTY_INDEX = "index";
  @javax.annotation.Nullable
  private Long index;

  public static final String JSON_PROPERTY_LABEL = "label";
  @javax.annotation.Nullable
  private String label;

  public static final String JSON_PROPERTY_MEDIA_TYPE = "mediaType";
  @javax.annotation.Nullable
  private String mediaType;

  public static final String JSON_PROPERTY_PATH = "path";
  @javax.annotation.Nullable
  private String path;

  public static final String JSON_PROPERTY_SIZE = "size";
  @javax.annotation.Nullable
  private String size;

  public AttachmentArchiveItemReadable() { 
  }

  @JsonCreator
  public AttachmentArchiveItemReadable(
    @JsonProperty(JSON_PROPERTY_INDEX) Long index, 
    @JsonProperty(JSON_PROPERTY_LABEL) String label, 
    @JsonProperty(JSON_PROPERTY_MEDIA_TYPE) String mediaType, 
    @JsonProperty(JSON_PROPERTY_PATH) String path, 
    @JsonProperty(JSON_PROPERTY_SIZE) String size
  ) {
  this();
    this.index = index;
    this.label = label;
    this.mediaType = mediaType;
    this.path = path;
    this.size = size;
  }

  /**
   * The position of the item within the archive.
   * @return index
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INDEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getIndex() {
    return index;
  }




  /**
   * The label for the archive item.
   * @return label
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LABEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLabel() {
    return label;
  }




  /**
   * The MIME type of the archive item.
   * @return mediaType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MEDIA_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMediaType() {
    return mediaType;
  }




  /**
   * The path of the archive item.
   * @return path
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPath() {
    return path;
  }




  /**
   * The size of the archive item.
   * @return size
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSize() {
    return size;
  }




  /**
   * Return true if this AttachmentArchiveItemReadable object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AttachmentArchiveItemReadable attachmentArchiveItemReadable = (AttachmentArchiveItemReadable) o;
    return Objects.equals(this.index, attachmentArchiveItemReadable.index) &&
        Objects.equals(this.label, attachmentArchiveItemReadable.label) &&
        Objects.equals(this.mediaType, attachmentArchiveItemReadable.mediaType) &&
        Objects.equals(this.path, attachmentArchiveItemReadable.path) &&
        Objects.equals(this.size, attachmentArchiveItemReadable.size);
  }

  @Override
  public int hashCode() {
    return Objects.hash(index, label, mediaType, path, size);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AttachmentArchiveItemReadable {\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    mediaType: ").append(toIndentedString(mediaType)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `index` to the URL query string
    if (getIndex() != null) {
      joiner.add(String.format(Locale.ROOT, "%sindex%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIndex()))));
    }

    // add `label` to the URL query string
    if (getLabel() != null) {
      joiner.add(String.format(Locale.ROOT, "%slabel%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLabel()))));
    }

    // add `mediaType` to the URL query string
    if (getMediaType() != null) {
      joiner.add(String.format(Locale.ROOT, "%smediaType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMediaType()))));
    }

    // add `path` to the URL query string
    if (getPath() != null) {
      joiner.add(String.format(Locale.ROOT, "%spath%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPath()))));
    }

    // add `size` to the URL query string
    if (getSize() != null) {
      joiner.add(String.format(Locale.ROOT, "%ssize%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSize()))));
    }

    return joiner.toString();
  }
}

