/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1bc87d9c91847a6f215496c203268482a08e6f70
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.jira.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.kestra.plugin.jira.client.invoker.ApiClient;
/**
 * The Atlassian provided system rules available.
 */
@JsonPropertyOrder({
  AvailableWorkflowSystemRule.JSON_PROPERTY_DESCRIPTION,
  AvailableWorkflowSystemRule.JSON_PROPERTY_INCOMPATIBLE_RULE_KEYS,
  AvailableWorkflowSystemRule.JSON_PROPERTY_IS_AVAILABLE_FOR_INITIAL_TRANSITION,
  AvailableWorkflowSystemRule.JSON_PROPERTY_IS_VISIBLE,
  AvailableWorkflowSystemRule.JSON_PROPERTY_NAME,
  AvailableWorkflowSystemRule.JSON_PROPERTY_RULE_KEY,
  AvailableWorkflowSystemRule.JSON_PROPERTY_RULE_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class AvailableWorkflowSystemRule {
  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nonnull
  private String description;

  public static final String JSON_PROPERTY_INCOMPATIBLE_RULE_KEYS = "incompatibleRuleKeys";
  @javax.annotation.Nonnull
  private List<String> incompatibleRuleKeys = new ArrayList<>();

  public static final String JSON_PROPERTY_IS_AVAILABLE_FOR_INITIAL_TRANSITION = "isAvailableForInitialTransition";
  @javax.annotation.Nonnull
  private Boolean isAvailableForInitialTransition;

  public static final String JSON_PROPERTY_IS_VISIBLE = "isVisible";
  @javax.annotation.Nonnull
  private Boolean isVisible;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_RULE_KEY = "ruleKey";
  @javax.annotation.Nonnull
  private String ruleKey;

  /**
   * The rule type.
   */
  public enum RuleTypeEnum {
    CONDITION(String.valueOf("Condition")),
    
    VALIDATOR(String.valueOf("Validator")),
    
    FUNCTION(String.valueOf("Function")),
    
    SCREEN(String.valueOf("Screen"));

    private String value;

    RuleTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RuleTypeEnum fromValue(String value) {
      for (RuleTypeEnum b : RuleTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_RULE_TYPE = "ruleType";
  @javax.annotation.Nonnull
  private RuleTypeEnum ruleType;

  public AvailableWorkflowSystemRule() { 
  }

  public AvailableWorkflowSystemRule description(@javax.annotation.Nonnull String description) {
    this.description = description;
    return this;
  }

  /**
   * The rule description.
   * @return description
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(@javax.annotation.Nonnull String description) {
    this.description = description;
  }


  public AvailableWorkflowSystemRule incompatibleRuleKeys(@javax.annotation.Nonnull List<String> incompatibleRuleKeys) {
    this.incompatibleRuleKeys = incompatibleRuleKeys;
    return this;
  }

  public AvailableWorkflowSystemRule addIncompatibleRuleKeysItem(String incompatibleRuleKeysItem) {
    if (this.incompatibleRuleKeys == null) {
      this.incompatibleRuleKeys = new ArrayList<>();
    }
    this.incompatibleRuleKeys.add(incompatibleRuleKeysItem);
    return this;
  }

  /**
   * List of rules that conflict with this one.
   * @return incompatibleRuleKeys
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_INCOMPATIBLE_RULE_KEYS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getIncompatibleRuleKeys() {
    return incompatibleRuleKeys;
  }


  @JsonProperty(value = JSON_PROPERTY_INCOMPATIBLE_RULE_KEYS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIncompatibleRuleKeys(@javax.annotation.Nonnull List<String> incompatibleRuleKeys) {
    this.incompatibleRuleKeys = incompatibleRuleKeys;
  }


  public AvailableWorkflowSystemRule isAvailableForInitialTransition(@javax.annotation.Nonnull Boolean isAvailableForInitialTransition) {
    this.isAvailableForInitialTransition = isAvailableForInitialTransition;
    return this;
  }

  /**
   * Whether the rule can be added added to an initial transition.
   * @return isAvailableForInitialTransition
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_IS_AVAILABLE_FOR_INITIAL_TRANSITION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getIsAvailableForInitialTransition() {
    return isAvailableForInitialTransition;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_AVAILABLE_FOR_INITIAL_TRANSITION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsAvailableForInitialTransition(@javax.annotation.Nonnull Boolean isAvailableForInitialTransition) {
    this.isAvailableForInitialTransition = isAvailableForInitialTransition;
  }


  public AvailableWorkflowSystemRule isVisible(@javax.annotation.Nonnull Boolean isVisible) {
    this.isVisible = isVisible;
    return this;
  }

  /**
   * Whether the rule is visible.
   * @return isVisible
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_IS_VISIBLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getIsVisible() {
    return isVisible;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_VISIBLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsVisible(@javax.annotation.Nonnull Boolean isVisible) {
    this.isVisible = isVisible;
  }


  public AvailableWorkflowSystemRule name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * The rule name.
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public AvailableWorkflowSystemRule ruleKey(@javax.annotation.Nonnull String ruleKey) {
    this.ruleKey = ruleKey;
    return this;
  }

  /**
   * The rule key.
   * @return ruleKey
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RULE_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getRuleKey() {
    return ruleKey;
  }


  @JsonProperty(value = JSON_PROPERTY_RULE_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRuleKey(@javax.annotation.Nonnull String ruleKey) {
    this.ruleKey = ruleKey;
  }


  public AvailableWorkflowSystemRule ruleType(@javax.annotation.Nonnull RuleTypeEnum ruleType) {
    this.ruleType = ruleType;
    return this;
  }

  /**
   * The rule type.
   * @return ruleType
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RULE_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public RuleTypeEnum getRuleType() {
    return ruleType;
  }


  @JsonProperty(value = JSON_PROPERTY_RULE_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRuleType(@javax.annotation.Nonnull RuleTypeEnum ruleType) {
    this.ruleType = ruleType;
  }


  /**
   * Return true if this AvailableWorkflowSystemRule object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AvailableWorkflowSystemRule availableWorkflowSystemRule = (AvailableWorkflowSystemRule) o;
    return Objects.equals(this.description, availableWorkflowSystemRule.description) &&
        Objects.equals(this.incompatibleRuleKeys, availableWorkflowSystemRule.incompatibleRuleKeys) &&
        Objects.equals(this.isAvailableForInitialTransition, availableWorkflowSystemRule.isAvailableForInitialTransition) &&
        Objects.equals(this.isVisible, availableWorkflowSystemRule.isVisible) &&
        Objects.equals(this.name, availableWorkflowSystemRule.name) &&
        Objects.equals(this.ruleKey, availableWorkflowSystemRule.ruleKey) &&
        Objects.equals(this.ruleType, availableWorkflowSystemRule.ruleType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, incompatibleRuleKeys, isAvailableForInitialTransition, isVisible, name, ruleKey, ruleType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AvailableWorkflowSystemRule {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    incompatibleRuleKeys: ").append(toIndentedString(incompatibleRuleKeys)).append("\n");
    sb.append("    isAvailableForInitialTransition: ").append(toIndentedString(isAvailableForInitialTransition)).append("\n");
    sb.append("    isVisible: ").append(toIndentedString(isVisible)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ruleKey: ").append(toIndentedString(ruleKey)).append("\n");
    sb.append("    ruleType: ").append(toIndentedString(ruleType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format(Locale.ROOT, "%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `incompatibleRuleKeys` to the URL query string
    if (getIncompatibleRuleKeys() != null) {
      for (int i = 0; i < getIncompatibleRuleKeys().size(); i++) {
        joiner.add(String.format(Locale.ROOT, "%sincompatibleRuleKeys%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getIncompatibleRuleKeys().get(i)))));
      }
    }

    // add `isAvailableForInitialTransition` to the URL query string
    if (getIsAvailableForInitialTransition() != null) {
      joiner.add(String.format(Locale.ROOT, "%sisAvailableForInitialTransition%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsAvailableForInitialTransition()))));
    }

    // add `isVisible` to the URL query string
    if (getIsVisible() != null) {
      joiner.add(String.format(Locale.ROOT, "%sisVisible%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsVisible()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `ruleKey` to the URL query string
    if (getRuleKey() != null) {
      joiner.add(String.format(Locale.ROOT, "%sruleKey%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRuleKey()))));
    }

    // add `ruleType` to the URL query string
    if (getRuleType() != null) {
      joiner.add(String.format(Locale.ROOT, "%sruleType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRuleType()))));
    }

    return joiner.toString();
  }
}

