/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1bc87d9c91847a6f215496c203268482a08e6f70
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.jira.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.kestra.plugin.jira.client.model.User;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.kestra.plugin.jira.client.invoker.ApiClient;
/**
 * BulkOperationProgress
 */
@JsonPropertyOrder({
  BulkOperationProgress.JSON_PROPERTY_CREATED,
  BulkOperationProgress.JSON_PROPERTY_FAILED_ACCESSIBLE_ISSUES,
  BulkOperationProgress.JSON_PROPERTY_INVALID_OR_INACCESSIBLE_ISSUE_COUNT,
  BulkOperationProgress.JSON_PROPERTY_PROCESSED_ACCESSIBLE_ISSUES,
  BulkOperationProgress.JSON_PROPERTY_PROGRESS_PERCENT,
  BulkOperationProgress.JSON_PROPERTY_STARTED,
  BulkOperationProgress.JSON_PROPERTY_STATUS,
  BulkOperationProgress.JSON_PROPERTY_SUBMITTED_BY,
  BulkOperationProgress.JSON_PROPERTY_TASK_ID,
  BulkOperationProgress.JSON_PROPERTY_TOTAL_ISSUE_COUNT,
  BulkOperationProgress.JSON_PROPERTY_UPDATED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class BulkOperationProgress {
  public static final String JSON_PROPERTY_CREATED = "created";
  @javax.annotation.Nullable
  private OffsetDateTime created;

  public static final String JSON_PROPERTY_FAILED_ACCESSIBLE_ISSUES = "failedAccessibleIssues";
  @javax.annotation.Nullable
  private Map<String, List<String>> failedAccessibleIssues = new HashMap<>();

  public static final String JSON_PROPERTY_INVALID_OR_INACCESSIBLE_ISSUE_COUNT = "invalidOrInaccessibleIssueCount";
  @javax.annotation.Nullable
  private Integer invalidOrInaccessibleIssueCount;

  public static final String JSON_PROPERTY_PROCESSED_ACCESSIBLE_ISSUES = "processedAccessibleIssues";
  @javax.annotation.Nullable
  private List<Long> processedAccessibleIssues = new ArrayList<>();

  public static final String JSON_PROPERTY_PROGRESS_PERCENT = "progressPercent";
  @javax.annotation.Nullable
  private Long progressPercent;

  public static final String JSON_PROPERTY_STARTED = "started";
  @javax.annotation.Nullable
  private OffsetDateTime started;

  /**
   * The status of the task.
   */
  public enum StatusEnum {
    ENQUEUED(String.valueOf("ENQUEUED")),
    
    RUNNING(String.valueOf("RUNNING")),
    
    COMPLETE(String.valueOf("COMPLETE")),
    
    FAILED(String.valueOf("FAILED")),
    
    CANCEL_REQUESTED(String.valueOf("CANCEL_REQUESTED")),
    
    CANCELLED(String.valueOf("CANCELLED")),
    
    DEAD(String.valueOf("DEAD"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private StatusEnum status;

  public static final String JSON_PROPERTY_SUBMITTED_BY = "submittedBy";
  @javax.annotation.Nullable
  private User submittedBy;

  public static final String JSON_PROPERTY_TASK_ID = "taskId";
  @javax.annotation.Nullable
  private String taskId;

  public static final String JSON_PROPERTY_TOTAL_ISSUE_COUNT = "totalIssueCount";
  @javax.annotation.Nullable
  private Integer totalIssueCount;

  public static final String JSON_PROPERTY_UPDATED = "updated";
  @javax.annotation.Nullable
  private OffsetDateTime updated;

  public BulkOperationProgress() { 
  }

  @JsonCreator
  public BulkOperationProgress(
    @JsonProperty(JSON_PROPERTY_TASK_ID) String taskId
  ) {
  this();
    this.taskId = taskId;
  }

  public BulkOperationProgress created(@javax.annotation.Nullable OffsetDateTime created) {
    this.created = created;
    return this;
  }

  /**
   * A timestamp of when the task was submitted.
   * @return created
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCreated() {
    return created;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreated(@javax.annotation.Nullable OffsetDateTime created) {
    this.created = created;
  }


  public BulkOperationProgress failedAccessibleIssues(@javax.annotation.Nullable Map<String, List<String>> failedAccessibleIssues) {
    this.failedAccessibleIssues = failedAccessibleIssues;
    return this;
  }

  public BulkOperationProgress putFailedAccessibleIssuesItem(String key, List<String> failedAccessibleIssuesItem) {
    if (this.failedAccessibleIssues == null) {
      this.failedAccessibleIssues = new HashMap<>();
    }
    this.failedAccessibleIssues.put(key, failedAccessibleIssuesItem);
    return this;
  }

  /**
   * Map of issue IDs for which the operation failed and that the user has permission to view, to their one or more reasons for failure. These reasons are open-ended text descriptions of the error and are not selected from a predefined list of standard reasons.
   * @return failedAccessibleIssues
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FAILED_ACCESSIBLE_ISSUES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, List<String>> getFailedAccessibleIssues() {
    return failedAccessibleIssues;
  }


  @JsonProperty(value = JSON_PROPERTY_FAILED_ACCESSIBLE_ISSUES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFailedAccessibleIssues(@javax.annotation.Nullable Map<String, List<String>> failedAccessibleIssues) {
    this.failedAccessibleIssues = failedAccessibleIssues;
  }


  public BulkOperationProgress invalidOrInaccessibleIssueCount(@javax.annotation.Nullable Integer invalidOrInaccessibleIssueCount) {
    this.invalidOrInaccessibleIssueCount = invalidOrInaccessibleIssueCount;
    return this;
  }

  /**
   * The number of issues that are either invalid or issues that the user doesn&#39;t have permission to view, regardless of the success or failure of the operation.
   * @return invalidOrInaccessibleIssueCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INVALID_OR_INACCESSIBLE_ISSUE_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getInvalidOrInaccessibleIssueCount() {
    return invalidOrInaccessibleIssueCount;
  }


  @JsonProperty(value = JSON_PROPERTY_INVALID_OR_INACCESSIBLE_ISSUE_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInvalidOrInaccessibleIssueCount(@javax.annotation.Nullable Integer invalidOrInaccessibleIssueCount) {
    this.invalidOrInaccessibleIssueCount = invalidOrInaccessibleIssueCount;
  }


  public BulkOperationProgress processedAccessibleIssues(@javax.annotation.Nullable List<Long> processedAccessibleIssues) {
    this.processedAccessibleIssues = processedAccessibleIssues;
    return this;
  }

  public BulkOperationProgress addProcessedAccessibleIssuesItem(Long processedAccessibleIssuesItem) {
    if (this.processedAccessibleIssues == null) {
      this.processedAccessibleIssues = new ArrayList<>();
    }
    this.processedAccessibleIssues.add(processedAccessibleIssuesItem);
    return this;
  }

  /**
   * List of issue IDs for which the operation was successful and that the user has permission to view.
   * @return processedAccessibleIssues
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROCESSED_ACCESSIBLE_ISSUES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<Long> getProcessedAccessibleIssues() {
    return processedAccessibleIssues;
  }


  @JsonProperty(value = JSON_PROPERTY_PROCESSED_ACCESSIBLE_ISSUES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProcessedAccessibleIssues(@javax.annotation.Nullable List<Long> processedAccessibleIssues) {
    this.processedAccessibleIssues = processedAccessibleIssues;
  }


  public BulkOperationProgress progressPercent(@javax.annotation.Nullable Long progressPercent) {
    this.progressPercent = progressPercent;
    return this;
  }

  /**
   * Progress of the task as a percentage.
   * @return progressPercent
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROGRESS_PERCENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getProgressPercent() {
    return progressPercent;
  }


  @JsonProperty(value = JSON_PROPERTY_PROGRESS_PERCENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProgressPercent(@javax.annotation.Nullable Long progressPercent) {
    this.progressPercent = progressPercent;
  }


  public BulkOperationProgress started(@javax.annotation.Nullable OffsetDateTime started) {
    this.started = started;
    return this;
  }

  /**
   * A timestamp of when the task was started.
   * @return started
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STARTED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getStarted() {
    return started;
  }


  @JsonProperty(value = JSON_PROPERTY_STARTED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStarted(@javax.annotation.Nullable OffsetDateTime started) {
    this.started = started;
  }


  public BulkOperationProgress status(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * The status of the task.
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public BulkOperationProgress submittedBy(@javax.annotation.Nullable User submittedBy) {
    this.submittedBy = submittedBy;
    return this;
  }

  /**
   * Get submittedBy
   * @return submittedBy
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUBMITTED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public User getSubmittedBy() {
    return submittedBy;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBMITTED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubmittedBy(@javax.annotation.Nullable User submittedBy) {
    this.submittedBy = submittedBy;
  }


  /**
   * The ID of the task.
   * @return taskId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TASK_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTaskId() {
    return taskId;
  }




  public BulkOperationProgress totalIssueCount(@javax.annotation.Nullable Integer totalIssueCount) {
    this.totalIssueCount = totalIssueCount;
    return this;
  }

  /**
   * The number of issues that the bulk operation was attempted on.
   * @return totalIssueCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_ISSUE_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTotalIssueCount() {
    return totalIssueCount;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_ISSUE_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalIssueCount(@javax.annotation.Nullable Integer totalIssueCount) {
    this.totalIssueCount = totalIssueCount;
  }


  public BulkOperationProgress updated(@javax.annotation.Nullable OffsetDateTime updated) {
    this.updated = updated;
    return this;
  }

  /**
   * A timestamp of when the task progress was last updated.
   * @return updated
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getUpdated() {
    return updated;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdated(@javax.annotation.Nullable OffsetDateTime updated) {
    this.updated = updated;
  }


  /**
   * Return true if this BulkOperationProgress object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkOperationProgress bulkOperationProgress = (BulkOperationProgress) o;
    return Objects.equals(this.created, bulkOperationProgress.created) &&
        Objects.equals(this.failedAccessibleIssues, bulkOperationProgress.failedAccessibleIssues) &&
        Objects.equals(this.invalidOrInaccessibleIssueCount, bulkOperationProgress.invalidOrInaccessibleIssueCount) &&
        Objects.equals(this.processedAccessibleIssues, bulkOperationProgress.processedAccessibleIssues) &&
        Objects.equals(this.progressPercent, bulkOperationProgress.progressPercent) &&
        Objects.equals(this.started, bulkOperationProgress.started) &&
        Objects.equals(this.status, bulkOperationProgress.status) &&
        Objects.equals(this.submittedBy, bulkOperationProgress.submittedBy) &&
        Objects.equals(this.taskId, bulkOperationProgress.taskId) &&
        Objects.equals(this.totalIssueCount, bulkOperationProgress.totalIssueCount) &&
        Objects.equals(this.updated, bulkOperationProgress.updated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(created, failedAccessibleIssues, invalidOrInaccessibleIssueCount, processedAccessibleIssues, progressPercent, started, status, submittedBy, taskId, totalIssueCount, updated);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkOperationProgress {\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    failedAccessibleIssues: ").append(toIndentedString(failedAccessibleIssues)).append("\n");
    sb.append("    invalidOrInaccessibleIssueCount: ").append(toIndentedString(invalidOrInaccessibleIssueCount)).append("\n");
    sb.append("    processedAccessibleIssues: ").append(toIndentedString(processedAccessibleIssues)).append("\n");
    sb.append("    progressPercent: ").append(toIndentedString(progressPercent)).append("\n");
    sb.append("    started: ").append(toIndentedString(started)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    submittedBy: ").append(toIndentedString(submittedBy)).append("\n");
    sb.append("    taskId: ").append(toIndentedString(taskId)).append("\n");
    sb.append("    totalIssueCount: ").append(toIndentedString(totalIssueCount)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `created` to the URL query string
    if (getCreated() != null) {
      joiner.add(String.format(Locale.ROOT, "%screated%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreated()))));
    }

    // add `failedAccessibleIssues` to the URL query string
    if (getFailedAccessibleIssues() != null) {
      for (String _key : getFailedAccessibleIssues().keySet()) {
        joiner.add(String.format(Locale.ROOT, "%sfailedAccessibleIssues%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getFailedAccessibleIssues().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getFailedAccessibleIssues().get(_key)))));
      }
    }

    // add `invalidOrInaccessibleIssueCount` to the URL query string
    if (getInvalidOrInaccessibleIssueCount() != null) {
      joiner.add(String.format(Locale.ROOT, "%sinvalidOrInaccessibleIssueCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getInvalidOrInaccessibleIssueCount()))));
    }

    // add `processedAccessibleIssues` to the URL query string
    if (getProcessedAccessibleIssues() != null) {
      for (int i = 0; i < getProcessedAccessibleIssues().size(); i++) {
        joiner.add(String.format(Locale.ROOT, "%sprocessedAccessibleIssues%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getProcessedAccessibleIssues().get(i)))));
      }
    }

    // add `progressPercent` to the URL query string
    if (getProgressPercent() != null) {
      joiner.add(String.format(Locale.ROOT, "%sprogressPercent%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProgressPercent()))));
    }

    // add `started` to the URL query string
    if (getStarted() != null) {
      joiner.add(String.format(Locale.ROOT, "%sstarted%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStarted()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `submittedBy` to the URL query string
    if (getSubmittedBy() != null) {
      joiner.add(getSubmittedBy().toUrlQueryString(prefix + "submittedBy" + suffix));
    }

    // add `taskId` to the URL query string
    if (getTaskId() != null) {
      joiner.add(String.format(Locale.ROOT, "%staskId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTaskId()))));
    }

    // add `totalIssueCount` to the URL query string
    if (getTotalIssueCount() != null) {
      joiner.add(String.format(Locale.ROOT, "%stotalIssueCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalIssueCount()))));
    }

    // add `updated` to the URL query string
    if (getUpdated() != null) {
      joiner.add(String.format(Locale.ROOT, "%supdated%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUpdated()))));
    }

    return joiner.toString();
  }
}

