/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1bc87d9c91847a6f215496c203268482a08e6f70
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.jira.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.kestra.plugin.jira.client.invoker.ApiClient;
/**
 * Card layout configuration.
 */
@JsonPropertyOrder({
  CardLayout.JSON_PROPERTY_SHOW_DAYS_IN_COLUMN
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class CardLayout {
  public static final String JSON_PROPERTY_SHOW_DAYS_IN_COLUMN = "showDaysInColumn";
  @javax.annotation.Nullable
  private Boolean showDaysInColumn = false;

  public CardLayout() { 
  }

  public CardLayout showDaysInColumn(@javax.annotation.Nullable Boolean showDaysInColumn) {
    this.showDaysInColumn = showDaysInColumn;
    return this;
  }

  /**
   * Whether to show days in column
   * @return showDaysInColumn
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SHOW_DAYS_IN_COLUMN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getShowDaysInColumn() {
    return showDaysInColumn;
  }


  @JsonProperty(value = JSON_PROPERTY_SHOW_DAYS_IN_COLUMN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShowDaysInColumn(@javax.annotation.Nullable Boolean showDaysInColumn) {
    this.showDaysInColumn = showDaysInColumn;
  }


  /**
   * Return true if this CardLayout object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardLayout cardLayout = (CardLayout) o;
    return Objects.equals(this.showDaysInColumn, cardLayout.showDaysInColumn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(showDaysInColumn);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardLayout {\n");
    sb.append("    showDaysInColumn: ").append(toIndentedString(showDaysInColumn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `showDaysInColumn` to the URL query string
    if (getShowDaysInColumn() != null) {
      joiner.add(String.format(Locale.ROOT, "%sshowDaysInColumn%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getShowDaysInColumn()))));
    }

    return joiner.toString();
  }
}

