/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1bc87d9c91847a6f215496c203268482a08e6f70
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.jira.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.kestra.plugin.jira.client.model.WorkflowRuleConfiguration;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.kestra.plugin.jira.client.invoker.ApiClient;
/**
 * The conditions group associated with the transition.
 */
@JsonPropertyOrder({
  ConditionGroupConfiguration.JSON_PROPERTY_CONDITION_GROUPS,
  ConditionGroupConfiguration.JSON_PROPERTY_CONDITIONS,
  ConditionGroupConfiguration.JSON_PROPERTY_OPERATION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class ConditionGroupConfiguration {
  public static final String JSON_PROPERTY_CONDITION_GROUPS = "conditionGroups";
  @javax.annotation.Nullable
  private List<ConditionGroupConfiguration> conditionGroups = new ArrayList<>();

  public static final String JSON_PROPERTY_CONDITIONS = "conditions";
  @javax.annotation.Nullable
  private List<WorkflowRuleConfiguration> conditions = new ArrayList<>();

  /**
   * Determines how the conditions in the group are evaluated. Accepts either &#x60;ANY&#x60; or &#x60;ALL&#x60;. If &#x60;ANY&#x60; is used, at least one condition in the group must be true for the group to evaluate to true. If &#x60;ALL&#x60; is used, all conditions in the group must be true for the group to evaluate to true.
   */
  public enum OperationEnum {
    ANY(String.valueOf("ANY")),
    
    ALL(String.valueOf("ALL"));

    private String value;

    OperationEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OperationEnum fromValue(String value) {
      for (OperationEnum b : OperationEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OPERATION = "operation";
  @javax.annotation.Nullable
  private OperationEnum operation;

  public ConditionGroupConfiguration() { 
  }

  public ConditionGroupConfiguration conditionGroups(@javax.annotation.Nullable List<ConditionGroupConfiguration> conditionGroups) {
    this.conditionGroups = conditionGroups;
    return this;
  }

  public ConditionGroupConfiguration addConditionGroupsItem(ConditionGroupConfiguration conditionGroupsItem) {
    if (this.conditionGroups == null) {
      this.conditionGroups = new ArrayList<>();
    }
    this.conditionGroups.add(conditionGroupsItem);
    return this;
  }

  /**
   * The nested conditions of the condition group.
   * @return conditionGroups
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONDITION_GROUPS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<ConditionGroupConfiguration> getConditionGroups() {
    return conditionGroups;
  }


  @JsonProperty(value = JSON_PROPERTY_CONDITION_GROUPS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConditionGroups(@javax.annotation.Nullable List<ConditionGroupConfiguration> conditionGroups) {
    this.conditionGroups = conditionGroups;
  }


  public ConditionGroupConfiguration conditions(@javax.annotation.Nullable List<WorkflowRuleConfiguration> conditions) {
    this.conditions = conditions;
    return this;
  }

  public ConditionGroupConfiguration addConditionsItem(WorkflowRuleConfiguration conditionsItem) {
    if (this.conditions == null) {
      this.conditions = new ArrayList<>();
    }
    this.conditions.add(conditionsItem);
    return this;
  }

  /**
   * The rules for this condition.
   * @return conditions
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONDITIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<WorkflowRuleConfiguration> getConditions() {
    return conditions;
  }


  @JsonProperty(value = JSON_PROPERTY_CONDITIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConditions(@javax.annotation.Nullable List<WorkflowRuleConfiguration> conditions) {
    this.conditions = conditions;
  }


  public ConditionGroupConfiguration operation(@javax.annotation.Nullable OperationEnum operation) {
    this.operation = operation;
    return this;
  }

  /**
   * Determines how the conditions in the group are evaluated. Accepts either &#x60;ANY&#x60; or &#x60;ALL&#x60;. If &#x60;ANY&#x60; is used, at least one condition in the group must be true for the group to evaluate to true. If &#x60;ALL&#x60; is used, all conditions in the group must be true for the group to evaluate to true.
   * @return operation
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OPERATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OperationEnum getOperation() {
    return operation;
  }


  @JsonProperty(value = JSON_PROPERTY_OPERATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperation(@javax.annotation.Nullable OperationEnum operation) {
    this.operation = operation;
  }


  /**
   * Return true if this ConditionGroupConfiguration object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConditionGroupConfiguration conditionGroupConfiguration = (ConditionGroupConfiguration) o;
    return Objects.equals(this.conditionGroups, conditionGroupConfiguration.conditionGroups) &&
        Objects.equals(this.conditions, conditionGroupConfiguration.conditions) &&
        Objects.equals(this.operation, conditionGroupConfiguration.operation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conditionGroups, conditions, operation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConditionGroupConfiguration {\n");
    sb.append("    conditionGroups: ").append(toIndentedString(conditionGroups)).append("\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `conditionGroups` to the URL query string
    if (getConditionGroups() != null) {
      for (int i = 0; i < getConditionGroups().size(); i++) {
        if (getConditionGroups().get(i) != null) {
          joiner.add(getConditionGroups().get(i).toUrlQueryString(String.format(Locale.ROOT, "%sconditionGroups%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `conditions` to the URL query string
    if (getConditions() != null) {
      for (int i = 0; i < getConditions().size(); i++) {
        if (getConditions().get(i) != null) {
          joiner.add(getConditions().get(i).toUrlQueryString(String.format(Locale.ROOT, "%sconditions%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `operation` to the URL query string
    if (getOperation() != null) {
      joiner.add(String.format(Locale.ROOT, "%soperation%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOperation()))));
    }

    return joiner.toString();
  }
}

