/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1bc87d9c91847a6f215496c203268482a08e6f70
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.jira.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.kestra.plugin.jira.client.model.CreateWorkflowStatusDetails;
import io.kestra.plugin.jira.client.model.CreateWorkflowTransitionDetails;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.kestra.plugin.jira.client.invoker.ApiClient;
/**
 * The details of a workflow.
 */
@JsonPropertyOrder({
  CreateWorkflowDetails.JSON_PROPERTY_DESCRIPTION,
  CreateWorkflowDetails.JSON_PROPERTY_NAME,
  CreateWorkflowDetails.JSON_PROPERTY_STATUSES,
  CreateWorkflowDetails.JSON_PROPERTY_TRANSITIONS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class CreateWorkflowDetails {
  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_STATUSES = "statuses";
  @javax.annotation.Nonnull
  private Set<CreateWorkflowStatusDetails> statuses = new LinkedHashSet<>();

  public static final String JSON_PROPERTY_TRANSITIONS = "transitions";
  @javax.annotation.Nonnull
  private List<CreateWorkflowTransitionDetails> transitions = new ArrayList<>();

  public CreateWorkflowDetails() { 
  }

  public CreateWorkflowDetails description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * The description of the workflow. The maximum length is 1000 characters.
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public CreateWorkflowDetails name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * The name of the workflow. The name must be unique. The maximum length is 255 characters. Characters can be separated by a whitespace but the name cannot start or end with a whitespace.
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public CreateWorkflowDetails statuses(@javax.annotation.Nonnull Set<CreateWorkflowStatusDetails> statuses) {
    this.statuses = statuses;
    return this;
  }

  public CreateWorkflowDetails addStatusesItem(CreateWorkflowStatusDetails statusesItem) {
    if (this.statuses == null) {
      this.statuses = new LinkedHashSet<>();
    }
    this.statuses.add(statusesItem);
    return this;
  }

  /**
   * The statuses of the workflow. Any status that does not include a transition is added to the workflow without a transition.
   * @return statuses
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUSES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Set<CreateWorkflowStatusDetails> getStatuses() {
    return statuses;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(value = JSON_PROPERTY_STATUSES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatuses(@javax.annotation.Nonnull Set<CreateWorkflowStatusDetails> statuses) {
    this.statuses = statuses;
  }


  public CreateWorkflowDetails transitions(@javax.annotation.Nonnull List<CreateWorkflowTransitionDetails> transitions) {
    this.transitions = transitions;
    return this;
  }

  public CreateWorkflowDetails addTransitionsItem(CreateWorkflowTransitionDetails transitionsItem) {
    if (this.transitions == null) {
      this.transitions = new ArrayList<>();
    }
    this.transitions.add(transitionsItem);
    return this;
  }

  /**
   * The transitions of the workflow. For the request to be valid, these transitions must:   *  include one *initial* transition.  *  not use the same name for a *global* and *directed* transition.  *  have a unique name for each *global* transition.  *  have a unique &#39;to&#39; status for each *global* transition.  *  have unique names for each transition from a status.  *  not have a &#39;from&#39; status on *initial* and *global* transitions.  *  have a &#39;from&#39; status on *directed* transitions.  All the transition statuses must be included in &#x60;statuses&#x60;.
   * @return transitions
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TRANSITIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<CreateWorkflowTransitionDetails> getTransitions() {
    return transitions;
  }


  @JsonProperty(value = JSON_PROPERTY_TRANSITIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransitions(@javax.annotation.Nonnull List<CreateWorkflowTransitionDetails> transitions) {
    this.transitions = transitions;
  }


  /**
   * Return true if this CreateWorkflowDetails object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateWorkflowDetails createWorkflowDetails = (CreateWorkflowDetails) o;
    return Objects.equals(this.description, createWorkflowDetails.description) &&
        Objects.equals(this.name, createWorkflowDetails.name) &&
        Objects.equals(this.statuses, createWorkflowDetails.statuses) &&
        Objects.equals(this.transitions, createWorkflowDetails.transitions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, name, statuses, transitions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateWorkflowDetails {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    statuses: ").append(toIndentedString(statuses)).append("\n");
    sb.append("    transitions: ").append(toIndentedString(transitions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format(Locale.ROOT, "%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `statuses` to the URL query string
    if (getStatuses() != null) {
      int i = 0;
      for (CreateWorkflowStatusDetails _item : getStatuses()) {
        if (_item != null) {
          joiner.add(_item.toUrlQueryString(String.format(Locale.ROOT, "%sstatuses%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
      i++;
    }

    // add `transitions` to the URL query string
    if (getTransitions() != null) {
      for (int i = 0; i < getTransitions().size(); i++) {
        if (getTransitions().get(i) != null) {
          joiner.add(getTransitions().get(i).toUrlQueryString(String.format(Locale.ROOT, "%stransitions%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

