/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1bc87d9c91847a6f215496c203268482a08e6f70
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.jira.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.kestra.plugin.jira.client.invoker.ApiClient;
/**
 * The field configuration for an issue type.
 */
@JsonPropertyOrder({
  FieldConfigurationIssueTypeItem.JSON_PROPERTY_FIELD_CONFIGURATION_ID,
  FieldConfigurationIssueTypeItem.JSON_PROPERTY_FIELD_CONFIGURATION_SCHEME_ID,
  FieldConfigurationIssueTypeItem.JSON_PROPERTY_ISSUE_TYPE_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class FieldConfigurationIssueTypeItem {
  public static final String JSON_PROPERTY_FIELD_CONFIGURATION_ID = "fieldConfigurationId";
  @javax.annotation.Nonnull
  private String fieldConfigurationId;

  public static final String JSON_PROPERTY_FIELD_CONFIGURATION_SCHEME_ID = "fieldConfigurationSchemeId";
  @javax.annotation.Nonnull
  private String fieldConfigurationSchemeId;

  public static final String JSON_PROPERTY_ISSUE_TYPE_ID = "issueTypeId";
  @javax.annotation.Nonnull
  private String issueTypeId;

  public FieldConfigurationIssueTypeItem() { 
  }

  public FieldConfigurationIssueTypeItem fieldConfigurationId(@javax.annotation.Nonnull String fieldConfigurationId) {
    this.fieldConfigurationId = fieldConfigurationId;
    return this;
  }

  /**
   * The ID of the field configuration.
   * @return fieldConfigurationId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FIELD_CONFIGURATION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getFieldConfigurationId() {
    return fieldConfigurationId;
  }


  @JsonProperty(value = JSON_PROPERTY_FIELD_CONFIGURATION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFieldConfigurationId(@javax.annotation.Nonnull String fieldConfigurationId) {
    this.fieldConfigurationId = fieldConfigurationId;
  }


  public FieldConfigurationIssueTypeItem fieldConfigurationSchemeId(@javax.annotation.Nonnull String fieldConfigurationSchemeId) {
    this.fieldConfigurationSchemeId = fieldConfigurationSchemeId;
    return this;
  }

  /**
   * The ID of the field configuration scheme.
   * @return fieldConfigurationSchemeId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FIELD_CONFIGURATION_SCHEME_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getFieldConfigurationSchemeId() {
    return fieldConfigurationSchemeId;
  }


  @JsonProperty(value = JSON_PROPERTY_FIELD_CONFIGURATION_SCHEME_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFieldConfigurationSchemeId(@javax.annotation.Nonnull String fieldConfigurationSchemeId) {
    this.fieldConfigurationSchemeId = fieldConfigurationSchemeId;
  }


  public FieldConfigurationIssueTypeItem issueTypeId(@javax.annotation.Nonnull String issueTypeId) {
    this.issueTypeId = issueTypeId;
    return this;
  }

  /**
   * The ID of the issue type or *default*. When set to *default* this field configuration issue type item applies to all issue types without a field configuration.
   * @return issueTypeId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ISSUE_TYPE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getIssueTypeId() {
    return issueTypeId;
  }


  @JsonProperty(value = JSON_PROPERTY_ISSUE_TYPE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIssueTypeId(@javax.annotation.Nonnull String issueTypeId) {
    this.issueTypeId = issueTypeId;
  }


  /**
   * Return true if this FieldConfigurationIssueTypeItem object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FieldConfigurationIssueTypeItem fieldConfigurationIssueTypeItem = (FieldConfigurationIssueTypeItem) o;
    return Objects.equals(this.fieldConfigurationId, fieldConfigurationIssueTypeItem.fieldConfigurationId) &&
        Objects.equals(this.fieldConfigurationSchemeId, fieldConfigurationIssueTypeItem.fieldConfigurationSchemeId) &&
        Objects.equals(this.issueTypeId, fieldConfigurationIssueTypeItem.issueTypeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fieldConfigurationId, fieldConfigurationSchemeId, issueTypeId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FieldConfigurationIssueTypeItem {\n");
    sb.append("    fieldConfigurationId: ").append(toIndentedString(fieldConfigurationId)).append("\n");
    sb.append("    fieldConfigurationSchemeId: ").append(toIndentedString(fieldConfigurationSchemeId)).append("\n");
    sb.append("    issueTypeId: ").append(toIndentedString(issueTypeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `fieldConfigurationId` to the URL query string
    if (getFieldConfigurationId() != null) {
      joiner.add(String.format(Locale.ROOT, "%sfieldConfigurationId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFieldConfigurationId()))));
    }

    // add `fieldConfigurationSchemeId` to the URL query string
    if (getFieldConfigurationSchemeId() != null) {
      joiner.add(String.format(Locale.ROOT, "%sfieldConfigurationSchemeId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFieldConfigurationSchemeId()))));
    }

    // add `issueTypeId` to the URL query string
    if (getIssueTypeId() != null) {
      joiner.add(String.format(Locale.ROOT, "%sissueTypeId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIssueTypeId()))));
    }

    return joiner.toString();
  }
}

