/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1bc87d9c91847a6f215496c203268482a08e6f70
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.jira.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.kestra.plugin.jira.client.invoker.ApiClient;
/**
 * GetAtlassianTeamResponse
 */
@JsonPropertyOrder({
  GetAtlassianTeamResponse.JSON_PROPERTY_CAPACITY,
  GetAtlassianTeamResponse.JSON_PROPERTY_ID,
  GetAtlassianTeamResponse.JSON_PROPERTY_ISSUE_SOURCE_ID,
  GetAtlassianTeamResponse.JSON_PROPERTY_PLANNING_STYLE,
  GetAtlassianTeamResponse.JSON_PROPERTY_SPRINT_LENGTH
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class GetAtlassianTeamResponse {
  public static final String JSON_PROPERTY_CAPACITY = "capacity";
  @javax.annotation.Nullable
  private Double capacity;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_ISSUE_SOURCE_ID = "issueSourceId";
  @javax.annotation.Nullable
  private Long issueSourceId;

  /**
   * The planning style for the Atlassian team. This is \&quot;Scrum\&quot; or \&quot;Kanban\&quot;.
   */
  public enum PlanningStyleEnum {
    SCRUM(String.valueOf("Scrum")),
    
    KANBAN(String.valueOf("Kanban"));

    private String value;

    PlanningStyleEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PlanningStyleEnum fromValue(String value) {
      for (PlanningStyleEnum b : PlanningStyleEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PLANNING_STYLE = "planningStyle";
  @javax.annotation.Nonnull
  private PlanningStyleEnum planningStyle;

  public static final String JSON_PROPERTY_SPRINT_LENGTH = "sprintLength";
  @javax.annotation.Nullable
  private Long sprintLength;

  public GetAtlassianTeamResponse() { 
  }

  public GetAtlassianTeamResponse capacity(@javax.annotation.Nullable Double capacity) {
    this.capacity = capacity;
    return this;
  }

  /**
   * The capacity for the Atlassian team.
   * @return capacity
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CAPACITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getCapacity() {
    return capacity;
  }


  @JsonProperty(value = JSON_PROPERTY_CAPACITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCapacity(@javax.annotation.Nullable Double capacity) {
    this.capacity = capacity;
  }


  public GetAtlassianTeamResponse id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * The Atlassian team ID.
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public GetAtlassianTeamResponse issueSourceId(@javax.annotation.Nullable Long issueSourceId) {
    this.issueSourceId = issueSourceId;
    return this;
  }

  /**
   * The ID of the issue source for the Atlassian team.
   * @return issueSourceId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ISSUE_SOURCE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getIssueSourceId() {
    return issueSourceId;
  }


  @JsonProperty(value = JSON_PROPERTY_ISSUE_SOURCE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssueSourceId(@javax.annotation.Nullable Long issueSourceId) {
    this.issueSourceId = issueSourceId;
  }


  public GetAtlassianTeamResponse planningStyle(@javax.annotation.Nonnull PlanningStyleEnum planningStyle) {
    this.planningStyle = planningStyle;
    return this;
  }

  /**
   * The planning style for the Atlassian team. This is \&quot;Scrum\&quot; or \&quot;Kanban\&quot;.
   * @return planningStyle
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PLANNING_STYLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public PlanningStyleEnum getPlanningStyle() {
    return planningStyle;
  }


  @JsonProperty(value = JSON_PROPERTY_PLANNING_STYLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPlanningStyle(@javax.annotation.Nonnull PlanningStyleEnum planningStyle) {
    this.planningStyle = planningStyle;
  }


  public GetAtlassianTeamResponse sprintLength(@javax.annotation.Nullable Long sprintLength) {
    this.sprintLength = sprintLength;
    return this;
  }

  /**
   * The sprint length for the Atlassian team.
   * @return sprintLength
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SPRINT_LENGTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getSprintLength() {
    return sprintLength;
  }


  @JsonProperty(value = JSON_PROPERTY_SPRINT_LENGTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSprintLength(@javax.annotation.Nullable Long sprintLength) {
    this.sprintLength = sprintLength;
  }


  /**
   * Return true if this GetAtlassianTeamResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetAtlassianTeamResponse getAtlassianTeamResponse = (GetAtlassianTeamResponse) o;
    return Objects.equals(this.capacity, getAtlassianTeamResponse.capacity) &&
        Objects.equals(this.id, getAtlassianTeamResponse.id) &&
        Objects.equals(this.issueSourceId, getAtlassianTeamResponse.issueSourceId) &&
        Objects.equals(this.planningStyle, getAtlassianTeamResponse.planningStyle) &&
        Objects.equals(this.sprintLength, getAtlassianTeamResponse.sprintLength);
  }

  @Override
  public int hashCode() {
    return Objects.hash(capacity, id, issueSourceId, planningStyle, sprintLength);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAtlassianTeamResponse {\n");
    sb.append("    capacity: ").append(toIndentedString(capacity)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    issueSourceId: ").append(toIndentedString(issueSourceId)).append("\n");
    sb.append("    planningStyle: ").append(toIndentedString(planningStyle)).append("\n");
    sb.append("    sprintLength: ").append(toIndentedString(sprintLength)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `capacity` to the URL query string
    if (getCapacity() != null) {
      joiner.add(String.format(Locale.ROOT, "%scapacity%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCapacity()))));
    }

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `issueSourceId` to the URL query string
    if (getIssueSourceId() != null) {
      joiner.add(String.format(Locale.ROOT, "%sissueSourceId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIssueSourceId()))));
    }

    // add `planningStyle` to the URL query string
    if (getPlanningStyle() != null) {
      joiner.add(String.format(Locale.ROOT, "%splanningStyle%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPlanningStyle()))));
    }

    // add `sprintLength` to the URL query string
    if (getSprintLength() != null) {
      joiner.add(String.format(Locale.ROOT, "%ssprintLength%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSprintLength()))));
    }

    return joiner.toString();
  }
}

