/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1bc87d9c91847a6f215496c203268482a08e6f70
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.jira.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.kestra.plugin.jira.client.invoker.ApiClient;
/**
 * The description of the page of issues loaded by the provided JQL query.This bean will be replacing IssuesJqlMetaDataBean bean as part of new &#x60;evaluate&#x60; endpoint
 */
@JsonPropertyOrder({
  JExpEvaluateIssuesJqlMetaDataBean.JSON_PROPERTY_IS_LAST,
  JExpEvaluateIssuesJqlMetaDataBean.JSON_PROPERTY_NEXT_PAGE_TOKEN
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class JExpEvaluateIssuesJqlMetaDataBean {
  public static final String JSON_PROPERTY_IS_LAST = "isLast";
  @javax.annotation.Nullable
  private Boolean isLast;

  public static final String JSON_PROPERTY_NEXT_PAGE_TOKEN = "nextPageToken";
  @javax.annotation.Nonnull
  private String nextPageToken;

  public JExpEvaluateIssuesJqlMetaDataBean() { 
  }

  @JsonCreator
  public JExpEvaluateIssuesJqlMetaDataBean(
    @JsonProperty(JSON_PROPERTY_IS_LAST) Boolean isLast
  ) {
  this();
    this.isLast = isLast;
  }

  /**
   * Indicates whether this is the last page of the paginated response.
   * @return isLast
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_LAST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsLast() {
    return isLast;
  }




  public JExpEvaluateIssuesJqlMetaDataBean nextPageToken(@javax.annotation.Nonnull String nextPageToken) {
    this.nextPageToken = nextPageToken;
    return this;
  }

  /**
   * Next Page token for the next page of issues.
   * @return nextPageToken
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NEXT_PAGE_TOKEN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getNextPageToken() {
    return nextPageToken;
  }


  @JsonProperty(value = JSON_PROPERTY_NEXT_PAGE_TOKEN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNextPageToken(@javax.annotation.Nonnull String nextPageToken) {
    this.nextPageToken = nextPageToken;
  }


  /**
   * Return true if this JExpEvaluateIssuesJqlMetaDataBean object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JExpEvaluateIssuesJqlMetaDataBean jexpEvaluateIssuesJqlMetaDataBean = (JExpEvaluateIssuesJqlMetaDataBean) o;
    return Objects.equals(this.isLast, jexpEvaluateIssuesJqlMetaDataBean.isLast) &&
        Objects.equals(this.nextPageToken, jexpEvaluateIssuesJqlMetaDataBean.nextPageToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isLast, nextPageToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JExpEvaluateIssuesJqlMetaDataBean {\n");
    sb.append("    isLast: ").append(toIndentedString(isLast)).append("\n");
    sb.append("    nextPageToken: ").append(toIndentedString(nextPageToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `isLast` to the URL query string
    if (getIsLast() != null) {
      joiner.add(String.format(Locale.ROOT, "%sisLast%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsLast()))));
    }

    // add `nextPageToken` to the URL query string
    if (getNextPageToken() != null) {
      joiner.add(String.format(Locale.ROOT, "%snextPageToken%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNextPageToken()))));
    }

    return joiner.toString();
  }
}

