/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1bc87d9c91847a6f215496c203268482a08e6f70
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.jira.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.kestra.plugin.jira.client.model.JiraExpressionEvalContextBean;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.kestra.plugin.jira.client.invoker.ApiClient;
/**
 * JiraExpressionEvalRequestBean
 */
@JsonPropertyOrder({
  JiraExpressionEvalRequestBean.JSON_PROPERTY_CONTEXT,
  JiraExpressionEvalRequestBean.JSON_PROPERTY_EXPRESSION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class JiraExpressionEvalRequestBean {
  public static final String JSON_PROPERTY_CONTEXT = "context";
  @javax.annotation.Nullable
  private JiraExpressionEvalContextBean context;

  public static final String JSON_PROPERTY_EXPRESSION = "expression";
  @javax.annotation.Nonnull
  private String expression;

  public JiraExpressionEvalRequestBean() { 
  }

  public JiraExpressionEvalRequestBean context(@javax.annotation.Nullable JiraExpressionEvalContextBean context) {
    this.context = context;
    return this;
  }

  /**
   * The context in which the Jira expression is evaluated.
   * @return context
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JiraExpressionEvalContextBean getContext() {
    return context;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContext(@javax.annotation.Nullable JiraExpressionEvalContextBean context) {
    this.context = context;
  }


  public JiraExpressionEvalRequestBean expression(@javax.annotation.Nonnull String expression) {
    this.expression = expression;
    return this;
  }

  /**
   * The Jira expression to evaluate.
   * @return expression
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EXPRESSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getExpression() {
    return expression;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPRESSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpression(@javax.annotation.Nonnull String expression) {
    this.expression = expression;
  }


  /**
   * Return true if this JiraExpressionEvalRequestBean object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JiraExpressionEvalRequestBean jiraExpressionEvalRequestBean = (JiraExpressionEvalRequestBean) o;
    return Objects.equals(this.context, jiraExpressionEvalRequestBean.context) &&
        Objects.equals(this.expression, jiraExpressionEvalRequestBean.expression);
  }

  @Override
  public int hashCode() {
    return Objects.hash(context, expression);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JiraExpressionEvalRequestBean {\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    expression: ").append(toIndentedString(expression)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `context` to the URL query string
    if (getContext() != null) {
      joiner.add(getContext().toUrlQueryString(prefix + "context" + suffix));
    }

    // add `expression` to the URL query string
    if (getExpression() != null) {
      joiner.add(String.format(Locale.ROOT, "%sexpression%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExpression()))));
    }

    return joiner.toString();
  }
}

