/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1bc87d9c91847a6f215496c203268482a08e6f70
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.jira.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.kestra.plugin.jira.client.model.ScreenScheme;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.kestra.plugin.jira.client.invoker.ApiClient;
/**
 * A page of items.
 */
@JsonPropertyOrder({
  PageBeanScreenScheme.JSON_PROPERTY_IS_LAST,
  PageBeanScreenScheme.JSON_PROPERTY_MAX_RESULTS,
  PageBeanScreenScheme.JSON_PROPERTY_NEXT_PAGE,
  PageBeanScreenScheme.JSON_PROPERTY_SELF,
  PageBeanScreenScheme.JSON_PROPERTY_START_AT,
  PageBeanScreenScheme.JSON_PROPERTY_TOTAL,
  PageBeanScreenScheme.JSON_PROPERTY_VALUES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class PageBeanScreenScheme {
  public static final String JSON_PROPERTY_IS_LAST = "isLast";
  @javax.annotation.Nullable
  private Boolean isLast;

  public static final String JSON_PROPERTY_MAX_RESULTS = "maxResults";
  @javax.annotation.Nullable
  private Integer maxResults;

  public static final String JSON_PROPERTY_NEXT_PAGE = "nextPage";
  @javax.annotation.Nullable
  private URI nextPage;

  public static final String JSON_PROPERTY_SELF = "self";
  @javax.annotation.Nullable
  private URI self;

  public static final String JSON_PROPERTY_START_AT = "startAt";
  @javax.annotation.Nullable
  private Long startAt;

  public static final String JSON_PROPERTY_TOTAL = "total";
  @javax.annotation.Nullable
  private Long total;

  public static final String JSON_PROPERTY_VALUES = "values";
  @javax.annotation.Nullable
  private List<ScreenScheme> values = new ArrayList<>();

  public PageBeanScreenScheme() { 
  }

  @JsonCreator
  public PageBeanScreenScheme(
    @JsonProperty(JSON_PROPERTY_IS_LAST) Boolean isLast, 
    @JsonProperty(JSON_PROPERTY_MAX_RESULTS) Integer maxResults, 
    @JsonProperty(JSON_PROPERTY_NEXT_PAGE) URI nextPage, 
    @JsonProperty(JSON_PROPERTY_SELF) URI self, 
    @JsonProperty(JSON_PROPERTY_START_AT) Long startAt, 
    @JsonProperty(JSON_PROPERTY_TOTAL) Long total, 
    @JsonProperty(JSON_PROPERTY_VALUES) List<ScreenScheme> values
  ) {
  this();
    this.isLast = isLast;
    this.maxResults = maxResults;
    this.nextPage = nextPage;
    this.self = self;
    this.startAt = startAt;
    this.total = total;
    this.values = values;
  }

  /**
   * Whether this is the last page.
   * @return isLast
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_LAST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsLast() {
    return isLast;
  }




  /**
   * The maximum number of items that could be returned.
   * @return maxResults
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_RESULTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getMaxResults() {
    return maxResults;
  }




  /**
   * If there is another page of results, the URL of the next page.
   * @return nextPage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NEXT_PAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public URI getNextPage() {
    return nextPage;
  }




  /**
   * The URL of the page.
   * @return self
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SELF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public URI getSelf() {
    return self;
  }




  /**
   * The index of the first item returned.
   * @return startAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_START_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getStartAt() {
    return startAt;
  }




  /**
   * The number of items returned.
   * @return total
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getTotal() {
    return total;
  }




  /**
   * The list of items.
   * @return values
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VALUES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<ScreenScheme> getValues() {
    return values;
  }




  /**
   * Return true if this PageBeanScreenScheme object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PageBeanScreenScheme pageBeanScreenScheme = (PageBeanScreenScheme) o;
    return Objects.equals(this.isLast, pageBeanScreenScheme.isLast) &&
        Objects.equals(this.maxResults, pageBeanScreenScheme.maxResults) &&
        Objects.equals(this.nextPage, pageBeanScreenScheme.nextPage) &&
        Objects.equals(this.self, pageBeanScreenScheme.self) &&
        Objects.equals(this.startAt, pageBeanScreenScheme.startAt) &&
        Objects.equals(this.total, pageBeanScreenScheme.total) &&
        Objects.equals(this.values, pageBeanScreenScheme.values);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isLast, maxResults, nextPage, self, startAt, total, values);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PageBeanScreenScheme {\n");
    sb.append("    isLast: ").append(toIndentedString(isLast)).append("\n");
    sb.append("    maxResults: ").append(toIndentedString(maxResults)).append("\n");
    sb.append("    nextPage: ").append(toIndentedString(nextPage)).append("\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    startAt: ").append(toIndentedString(startAt)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `isLast` to the URL query string
    if (getIsLast() != null) {
      joiner.add(String.format(Locale.ROOT, "%sisLast%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsLast()))));
    }

    // add `maxResults` to the URL query string
    if (getMaxResults() != null) {
      joiner.add(String.format(Locale.ROOT, "%smaxResults%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMaxResults()))));
    }

    // add `nextPage` to the URL query string
    if (getNextPage() != null) {
      joiner.add(String.format(Locale.ROOT, "%snextPage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNextPage()))));
    }

    // add `self` to the URL query string
    if (getSelf() != null) {
      joiner.add(String.format(Locale.ROOT, "%sself%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSelf()))));
    }

    // add `startAt` to the URL query string
    if (getStartAt() != null) {
      joiner.add(String.format(Locale.ROOT, "%sstartAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStartAt()))));
    }

    // add `total` to the URL query string
    if (getTotal() != null) {
      joiner.add(String.format(Locale.ROOT, "%stotal%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotal()))));
    }

    // add `values` to the URL query string
    if (getValues() != null) {
      for (int i = 0; i < getValues().size(); i++) {
        if (getValues().get(i) != null) {
          joiner.add(getValues().get(i).toUrlQueryString(String.format(Locale.ROOT, "%svalues%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

