/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1bc87d9c91847a6f215496c203268482a08e6f70
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.jira.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.kestra.plugin.jira.client.model.ProjectIssueTypeMapping;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.kestra.plugin.jira.client.invoker.ApiClient;
/**
 * The project and issue type mappings.
 */
@JsonPropertyOrder({
  ProjectIssueTypeMappings.JSON_PROPERTY_MAPPINGS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class ProjectIssueTypeMappings {
  public static final String JSON_PROPERTY_MAPPINGS = "mappings";
  @javax.annotation.Nonnull
  private List<ProjectIssueTypeMapping> mappings = new ArrayList<>();

  public ProjectIssueTypeMappings() { 
  }

  public ProjectIssueTypeMappings mappings(@javax.annotation.Nonnull List<ProjectIssueTypeMapping> mappings) {
    this.mappings = mappings;
    return this;
  }

  public ProjectIssueTypeMappings addMappingsItem(ProjectIssueTypeMapping mappingsItem) {
    if (this.mappings == null) {
      this.mappings = new ArrayList<>();
    }
    this.mappings.add(mappingsItem);
    return this;
  }

  /**
   * The project and issue type mappings.
   * @return mappings
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MAPPINGS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<ProjectIssueTypeMapping> getMappings() {
    return mappings;
  }


  @JsonProperty(value = JSON_PROPERTY_MAPPINGS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMappings(@javax.annotation.Nonnull List<ProjectIssueTypeMapping> mappings) {
    this.mappings = mappings;
  }


  /**
   * Return true if this ProjectIssueTypeMappings object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectIssueTypeMappings projectIssueTypeMappings = (ProjectIssueTypeMappings) o;
    return Objects.equals(this.mappings, projectIssueTypeMappings.mappings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mappings);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectIssueTypeMappings {\n");
    sb.append("    mappings: ").append(toIndentedString(mappings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `mappings` to the URL query string
    if (getMappings() != null) {
      for (int i = 0; i < getMappings().size(); i++) {
        if (getMappings().get(i) != null) {
          joiner.add(getMappings().get(i).toUrlQueryString(String.format(Locale.ROOT, "%smappings%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

