/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1bc87d9c91847a6f215496c203268482a08e6f70
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.jira.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.kestra.plugin.jira.client.model.Application;
import io.kestra.plugin.jira.client.model.RemoteObject;
import java.net.URI;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.kestra.plugin.jira.client.invoker.ApiClient;
/**
 * Details of an issue remote link.
 */
@JsonPropertyOrder({
  RemoteIssueLink.JSON_PROPERTY_APPLICATION,
  RemoteIssueLink.JSON_PROPERTY_GLOBAL_ID,
  RemoteIssueLink.JSON_PROPERTY_ID,
  RemoteIssueLink.JSON_PROPERTY_OBJECT,
  RemoteIssueLink.JSON_PROPERTY_RELATIONSHIP,
  RemoteIssueLink.JSON_PROPERTY_SELF
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class RemoteIssueLink {
  public static final String JSON_PROPERTY_APPLICATION = "application";
  @javax.annotation.Nullable
  private Application application;

  public static final String JSON_PROPERTY_GLOBAL_ID = "globalId";
  @javax.annotation.Nullable
  private String globalId;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_OBJECT = "object";
  @javax.annotation.Nullable
  private RemoteObject _object;

  public static final String JSON_PROPERTY_RELATIONSHIP = "relationship";
  @javax.annotation.Nullable
  private String relationship;

  public static final String JSON_PROPERTY_SELF = "self";
  @javax.annotation.Nullable
  private URI self;

  public RemoteIssueLink() { 
  }

  public RemoteIssueLink application(@javax.annotation.Nullable Application application) {
    this.application = application;
    return this;
  }

  /**
   * Details of the remote application the linked item is in.
   * @return application
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_APPLICATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Application getApplication() {
    return application;
  }


  @JsonProperty(value = JSON_PROPERTY_APPLICATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApplication(@javax.annotation.Nullable Application application) {
    this.application = application;
  }


  public RemoteIssueLink globalId(@javax.annotation.Nullable String globalId) {
    this.globalId = globalId;
    return this;
  }

  /**
   * The global ID of the link, such as the ID of the item on the remote system.
   * @return globalId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GLOBAL_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getGlobalId() {
    return globalId;
  }


  @JsonProperty(value = JSON_PROPERTY_GLOBAL_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGlobalId(@javax.annotation.Nullable String globalId) {
    this.globalId = globalId;
  }


  public RemoteIssueLink id(@javax.annotation.Nullable Long id) {
    this.id = id;
    return this;
  }

  /**
   * The ID of the link.
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable Long id) {
    this.id = id;
  }


  public RemoteIssueLink _object(@javax.annotation.Nullable RemoteObject _object) {
    this._object = _object;
    return this;
  }

  /**
   * Details of the item linked to.
   * @return _object
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OBJECT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public RemoteObject getObject() {
    return _object;
  }


  @JsonProperty(value = JSON_PROPERTY_OBJECT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setObject(@javax.annotation.Nullable RemoteObject _object) {
    this._object = _object;
  }


  public RemoteIssueLink relationship(@javax.annotation.Nullable String relationship) {
    this.relationship = relationship;
    return this;
  }

  /**
   * Description of the relationship between the issue and the linked item.
   * @return relationship
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RELATIONSHIP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRelationship() {
    return relationship;
  }


  @JsonProperty(value = JSON_PROPERTY_RELATIONSHIP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelationship(@javax.annotation.Nullable String relationship) {
    this.relationship = relationship;
  }


  public RemoteIssueLink self(@javax.annotation.Nullable URI self) {
    this.self = self;
    return this;
  }

  /**
   * The URL of the link.
   * @return self
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SELF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public URI getSelf() {
    return self;
  }


  @JsonProperty(value = JSON_PROPERTY_SELF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSelf(@javax.annotation.Nullable URI self) {
    this.self = self;
  }


  /**
   * Return true if this RemoteIssueLink object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RemoteIssueLink remoteIssueLink = (RemoteIssueLink) o;
    return Objects.equals(this.application, remoteIssueLink.application) &&
        Objects.equals(this.globalId, remoteIssueLink.globalId) &&
        Objects.equals(this.id, remoteIssueLink.id) &&
        Objects.equals(this._object, remoteIssueLink._object) &&
        Objects.equals(this.relationship, remoteIssueLink.relationship) &&
        Objects.equals(this.self, remoteIssueLink.self);
  }

  @Override
  public int hashCode() {
    return Objects.hash(application, globalId, id, _object, relationship, self);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RemoteIssueLink {\n");
    sb.append("    application: ").append(toIndentedString(application)).append("\n");
    sb.append("    globalId: ").append(toIndentedString(globalId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    relationship: ").append(toIndentedString(relationship)).append("\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `application` to the URL query string
    if (getApplication() != null) {
      joiner.add(String.format(Locale.ROOT, "%sapplication%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getApplication()))));
    }

    // add `globalId` to the URL query string
    if (getGlobalId() != null) {
      joiner.add(String.format(Locale.ROOT, "%sglobalId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGlobalId()))));
    }

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `object` to the URL query string
    if (getObject() != null) {
      joiner.add(String.format(Locale.ROOT, "%sobject%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getObject()))));
    }

    // add `relationship` to the URL query string
    if (getRelationship() != null) {
      joiner.add(String.format(Locale.ROOT, "%srelationship%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRelationship()))));
    }

    // add `self` to the URL query string
    if (getSelf() != null) {
      joiner.add(String.format(Locale.ROOT, "%sself%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSelf()))));
    }

    return joiner.toString();
  }
}

