/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1bc87d9c91847a6f215496c203268482a08e6f70
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.jira.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kestra.plugin.jira.client.model.ProjectCreateResourceIdentifier;
import io.kestra.plugin.jira.client.model.RolePayload;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import io.kestra.plugin.jira.client.invoker.JSON;

/**
 * RolesCapabilityPayload
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class RolesCapabilityPayload {
  public static final String SERIALIZED_NAME_ROLE_TO_PROJECT_ACTORS = "roleToProjectActors";
  @SerializedName(SERIALIZED_NAME_ROLE_TO_PROJECT_ACTORS)
  @javax.annotation.Nullable
  private Map<String, List<ProjectCreateResourceIdentifier>> roleToProjectActors = new HashMap<>();

  public static final String SERIALIZED_NAME_ROLES = "roles";
  @SerializedName(SERIALIZED_NAME_ROLES)
  @javax.annotation.Nullable
  private List<RolePayload> roles = new ArrayList<>();

  public RolesCapabilityPayload() {
  }

  public RolesCapabilityPayload roleToProjectActors(@javax.annotation.Nullable Map<String, List<ProjectCreateResourceIdentifier>> roleToProjectActors) {
    this.roleToProjectActors = roleToProjectActors;
    return this;
  }

  public RolesCapabilityPayload putRoleToProjectActorsItem(String key, List<ProjectCreateResourceIdentifier> roleToProjectActorsItem) {
    if (this.roleToProjectActors == null) {
      this.roleToProjectActors = new HashMap<>();
    }
    this.roleToProjectActors.put(key, roleToProjectActorsItem);
    return this;
  }

  /**
   * A map of role PCRI (can be ID or REF) to a list of user or group PCRI IDs to associate with the role and project.
   * @return roleToProjectActors
   */
  @javax.annotation.Nullable
  public Map<String, List<ProjectCreateResourceIdentifier>> getRoleToProjectActors() {
    return roleToProjectActors;
  }

  public void setRoleToProjectActors(@javax.annotation.Nullable Map<String, List<ProjectCreateResourceIdentifier>> roleToProjectActors) {
    this.roleToProjectActors = roleToProjectActors;
  }


  public RolesCapabilityPayload roles(@javax.annotation.Nullable List<RolePayload> roles) {
    this.roles = roles;
    return this;
  }

  public RolesCapabilityPayload addRolesItem(RolePayload rolesItem) {
    if (this.roles == null) {
      this.roles = new ArrayList<>();
    }
    this.roles.add(rolesItem);
    return this;
  }

  /**
   * The list of roles to create.
   * @return roles
   */
  @javax.annotation.Nullable
  public List<RolePayload> getRoles() {
    return roles;
  }

  public void setRoles(@javax.annotation.Nullable List<RolePayload> roles) {
    this.roles = roles;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RolesCapabilityPayload rolesCapabilityPayload = (RolesCapabilityPayload) o;
    return Objects.equals(this.roleToProjectActors, rolesCapabilityPayload.roleToProjectActors) &&
        Objects.equals(this.roles, rolesCapabilityPayload.roles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(roleToProjectActors, roles);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RolesCapabilityPayload {\n");
    sb.append("    roleToProjectActors: ").append(toIndentedString(roleToProjectActors)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("roleToProjectActors", "roles"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RolesCapabilityPayload
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RolesCapabilityPayload.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in RolesCapabilityPayload is not found in the empty JSON string", RolesCapabilityPayload.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RolesCapabilityPayload.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `RolesCapabilityPayload` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("roles") != null && !jsonObj.get("roles").isJsonNull()) {
        JsonArray jsonArrayroles = jsonObj.getAsJsonArray("roles");
        if (jsonArrayroles != null) {
          // ensure the json data is an array
          if (!jsonObj.get("roles").isJsonArray()) {
            throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `roles` to be an array in the JSON string but got `%s`", jsonObj.get("roles").toString()));
          }

          // validate the optional field `roles` (array)
          for (int i = 0; i < jsonArrayroles.size(); i++) {
            RolePayload.validateJsonElement(jsonArrayroles.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RolesCapabilityPayload.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RolesCapabilityPayload' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RolesCapabilityPayload> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RolesCapabilityPayload.class));

       return (TypeAdapter<T>) new TypeAdapter<RolesCapabilityPayload>() {
           @Override
           public void write(JsonWriter out, RolesCapabilityPayload value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RolesCapabilityPayload read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RolesCapabilityPayload given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RolesCapabilityPayload
   * @throws IOException if the JSON string is invalid with respect to RolesCapabilityPayload
   */
  public static RolesCapabilityPayload fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RolesCapabilityPayload.class);
  }

  /**
   * Convert an instance of RolesCapabilityPayload to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

