/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1bc87d9c91847a6f215496c203268482a08e6f70
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.jira.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.kestra.plugin.jira.client.model.ProjectCreateResourceIdentifier;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.kestra.plugin.jira.client.invoker.ApiClient;
/**
 * Defines the payload for the screen schemes. See https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-screen-schemes/\\#api-rest-api-3-screenscheme-post
 */
@JsonPropertyOrder({
  ScreenSchemePayload.JSON_PROPERTY_DEFAULT_SCREEN,
  ScreenSchemePayload.JSON_PROPERTY_DESCRIPTION,
  ScreenSchemePayload.JSON_PROPERTY_NAME,
  ScreenSchemePayload.JSON_PROPERTY_PCRI,
  ScreenSchemePayload.JSON_PROPERTY_SCREENS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class ScreenSchemePayload {
  public static final String JSON_PROPERTY_DEFAULT_SCREEN = "defaultScreen";
  @javax.annotation.Nullable
  private ProjectCreateResourceIdentifier defaultScreen;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_PCRI = "pcri";
  @javax.annotation.Nullable
  private ProjectCreateResourceIdentifier pcri;

  public static final String JSON_PROPERTY_SCREENS = "screens";
  @javax.annotation.Nullable
  private Map<String, ProjectCreateResourceIdentifier> screens = new HashMap<>();

  public ScreenSchemePayload() { 
  }

  public ScreenSchemePayload defaultScreen(@javax.annotation.Nullable ProjectCreateResourceIdentifier defaultScreen) {
    this.defaultScreen = defaultScreen;
    return this;
  }

  /**
   * Get defaultScreen
   * @return defaultScreen
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEFAULT_SCREEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ProjectCreateResourceIdentifier getDefaultScreen() {
    return defaultScreen;
  }


  @JsonProperty(value = JSON_PROPERTY_DEFAULT_SCREEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultScreen(@javax.annotation.Nullable ProjectCreateResourceIdentifier defaultScreen) {
    this.defaultScreen = defaultScreen;
  }


  public ScreenSchemePayload description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * The description of the screen scheme
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public ScreenSchemePayload name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * The name of the screen scheme
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public ScreenSchemePayload pcri(@javax.annotation.Nullable ProjectCreateResourceIdentifier pcri) {
    this.pcri = pcri;
    return this;
  }

  /**
   * Get pcri
   * @return pcri
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PCRI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ProjectCreateResourceIdentifier getPcri() {
    return pcri;
  }


  @JsonProperty(value = JSON_PROPERTY_PCRI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPcri(@javax.annotation.Nullable ProjectCreateResourceIdentifier pcri) {
    this.pcri = pcri;
  }


  public ScreenSchemePayload screens(@javax.annotation.Nullable Map<String, ProjectCreateResourceIdentifier> screens) {
    this.screens = screens;
    return this;
  }

  public ScreenSchemePayload putScreensItem(String key, ProjectCreateResourceIdentifier screensItem) {
    if (this.screens == null) {
      this.screens = new HashMap<>();
    }
    this.screens.put(key, screensItem);
    return this;
  }

  /**
   * Similar to the field layout scheme those mappings allow users to set different screens for different operations: default - always there, applied to all operations that don&#39;t have an explicit mapping &#x60;create&#x60;, &#x60;view&#x60;, &#x60;edit&#x60; - specific operations that are available and users can assign a different screen for each one of them https://support.atlassian.com/jira-cloud-administration/docs/manage-screen-schemes/\\#Associating-a-screen-with-an-issue-operation
   * @return screens
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCREENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, ProjectCreateResourceIdentifier> getScreens() {
    return screens;
  }


  @JsonProperty(value = JSON_PROPERTY_SCREENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScreens(@javax.annotation.Nullable Map<String, ProjectCreateResourceIdentifier> screens) {
    this.screens = screens;
  }


  /**
   * Return true if this ScreenSchemePayload object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScreenSchemePayload screenSchemePayload = (ScreenSchemePayload) o;
    return Objects.equals(this.defaultScreen, screenSchemePayload.defaultScreen) &&
        Objects.equals(this.description, screenSchemePayload.description) &&
        Objects.equals(this.name, screenSchemePayload.name) &&
        Objects.equals(this.pcri, screenSchemePayload.pcri) &&
        Objects.equals(this.screens, screenSchemePayload.screens);
  }

  @Override
  public int hashCode() {
    return Objects.hash(defaultScreen, description, name, pcri, screens);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScreenSchemePayload {\n");
    sb.append("    defaultScreen: ").append(toIndentedString(defaultScreen)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pcri: ").append(toIndentedString(pcri)).append("\n");
    sb.append("    screens: ").append(toIndentedString(screens)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `defaultScreen` to the URL query string
    if (getDefaultScreen() != null) {
      joiner.add(getDefaultScreen().toUrlQueryString(prefix + "defaultScreen" + suffix));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format(Locale.ROOT, "%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `pcri` to the URL query string
    if (getPcri() != null) {
      joiner.add(getPcri().toUrlQueryString(prefix + "pcri" + suffix));
    }

    // add `screens` to the URL query string
    if (getScreens() != null) {
      for (String _key : getScreens().keySet()) {
        if (getScreens().get(_key) != null) {
          joiner.add(getScreens().get(_key).toUrlQueryString(String.format(Locale.ROOT, "%sscreens%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

