/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1bc87d9c91847a6f215496c203268482a08e6f70
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.jira.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.kestra.plugin.jira.client.invoker.ApiClient;
/**
 * Time tracking details.
 */
@JsonPropertyOrder({
  TimeTrackingDetails.JSON_PROPERTY_ORIGINAL_ESTIMATE,
  TimeTrackingDetails.JSON_PROPERTY_ORIGINAL_ESTIMATE_SECONDS,
  TimeTrackingDetails.JSON_PROPERTY_REMAINING_ESTIMATE,
  TimeTrackingDetails.JSON_PROPERTY_REMAINING_ESTIMATE_SECONDS,
  TimeTrackingDetails.JSON_PROPERTY_TIME_SPENT,
  TimeTrackingDetails.JSON_PROPERTY_TIME_SPENT_SECONDS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class TimeTrackingDetails {
  public static final String JSON_PROPERTY_ORIGINAL_ESTIMATE = "originalEstimate";
  @javax.annotation.Nullable
  private String originalEstimate;

  public static final String JSON_PROPERTY_ORIGINAL_ESTIMATE_SECONDS = "originalEstimateSeconds";
  @javax.annotation.Nullable
  private Long originalEstimateSeconds;

  public static final String JSON_PROPERTY_REMAINING_ESTIMATE = "remainingEstimate";
  @javax.annotation.Nullable
  private String remainingEstimate;

  public static final String JSON_PROPERTY_REMAINING_ESTIMATE_SECONDS = "remainingEstimateSeconds";
  @javax.annotation.Nullable
  private Long remainingEstimateSeconds;

  public static final String JSON_PROPERTY_TIME_SPENT = "timeSpent";
  @javax.annotation.Nullable
  private String timeSpent;

  public static final String JSON_PROPERTY_TIME_SPENT_SECONDS = "timeSpentSeconds";
  @javax.annotation.Nullable
  private Long timeSpentSeconds;

  public TimeTrackingDetails() { 
  }

  @JsonCreator
  public TimeTrackingDetails(
    @JsonProperty(JSON_PROPERTY_ORIGINAL_ESTIMATE) String originalEstimate, 
    @JsonProperty(JSON_PROPERTY_ORIGINAL_ESTIMATE_SECONDS) Long originalEstimateSeconds, 
    @JsonProperty(JSON_PROPERTY_REMAINING_ESTIMATE) String remainingEstimate, 
    @JsonProperty(JSON_PROPERTY_REMAINING_ESTIMATE_SECONDS) Long remainingEstimateSeconds, 
    @JsonProperty(JSON_PROPERTY_TIME_SPENT) String timeSpent, 
    @JsonProperty(JSON_PROPERTY_TIME_SPENT_SECONDS) Long timeSpentSeconds
  ) {
  this();
    this.originalEstimate = originalEstimate;
    this.originalEstimateSeconds = originalEstimateSeconds;
    this.remainingEstimate = remainingEstimate;
    this.remainingEstimateSeconds = remainingEstimateSeconds;
    this.timeSpent = timeSpent;
    this.timeSpentSeconds = timeSpentSeconds;
  }

  /**
   * The original estimate of time needed for this issue in readable format.
   * @return originalEstimate
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ORIGINAL_ESTIMATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getOriginalEstimate() {
    return originalEstimate;
  }




  /**
   * The original estimate of time needed for this issue in seconds.
   * @return originalEstimateSeconds
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ORIGINAL_ESTIMATE_SECONDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getOriginalEstimateSeconds() {
    return originalEstimateSeconds;
  }




  /**
   * The remaining estimate of time needed for this issue in readable format.
   * @return remainingEstimate
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REMAINING_ESTIMATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRemainingEstimate() {
    return remainingEstimate;
  }




  /**
   * The remaining estimate of time needed for this issue in seconds.
   * @return remainingEstimateSeconds
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REMAINING_ESTIMATE_SECONDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getRemainingEstimateSeconds() {
    return remainingEstimateSeconds;
  }




  /**
   * Time worked on this issue in readable format.
   * @return timeSpent
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIME_SPENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTimeSpent() {
    return timeSpent;
  }




  /**
   * Time worked on this issue in seconds.
   * @return timeSpentSeconds
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIME_SPENT_SECONDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getTimeSpentSeconds() {
    return timeSpentSeconds;
  }




  /**
   * Return true if this TimeTrackingDetails object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeTrackingDetails timeTrackingDetails = (TimeTrackingDetails) o;
    return Objects.equals(this.originalEstimate, timeTrackingDetails.originalEstimate) &&
        Objects.equals(this.originalEstimateSeconds, timeTrackingDetails.originalEstimateSeconds) &&
        Objects.equals(this.remainingEstimate, timeTrackingDetails.remainingEstimate) &&
        Objects.equals(this.remainingEstimateSeconds, timeTrackingDetails.remainingEstimateSeconds) &&
        Objects.equals(this.timeSpent, timeTrackingDetails.timeSpent) &&
        Objects.equals(this.timeSpentSeconds, timeTrackingDetails.timeSpentSeconds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(originalEstimate, originalEstimateSeconds, remainingEstimate, remainingEstimateSeconds, timeSpent, timeSpentSeconds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeTrackingDetails {\n");
    sb.append("    originalEstimate: ").append(toIndentedString(originalEstimate)).append("\n");
    sb.append("    originalEstimateSeconds: ").append(toIndentedString(originalEstimateSeconds)).append("\n");
    sb.append("    remainingEstimate: ").append(toIndentedString(remainingEstimate)).append("\n");
    sb.append("    remainingEstimateSeconds: ").append(toIndentedString(remainingEstimateSeconds)).append("\n");
    sb.append("    timeSpent: ").append(toIndentedString(timeSpent)).append("\n");
    sb.append("    timeSpentSeconds: ").append(toIndentedString(timeSpentSeconds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `originalEstimate` to the URL query string
    if (getOriginalEstimate() != null) {
      joiner.add(String.format(Locale.ROOT, "%soriginalEstimate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOriginalEstimate()))));
    }

    // add `originalEstimateSeconds` to the URL query string
    if (getOriginalEstimateSeconds() != null) {
      joiner.add(String.format(Locale.ROOT, "%soriginalEstimateSeconds%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOriginalEstimateSeconds()))));
    }

    // add `remainingEstimate` to the URL query string
    if (getRemainingEstimate() != null) {
      joiner.add(String.format(Locale.ROOT, "%sremainingEstimate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRemainingEstimate()))));
    }

    // add `remainingEstimateSeconds` to the URL query string
    if (getRemainingEstimateSeconds() != null) {
      joiner.add(String.format(Locale.ROOT, "%sremainingEstimateSeconds%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRemainingEstimateSeconds()))));
    }

    // add `timeSpent` to the URL query string
    if (getTimeSpent() != null) {
      joiner.add(String.format(Locale.ROOT, "%stimeSpent%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimeSpent()))));
    }

    // add `timeSpentSeconds` to the URL query string
    if (getTimeSpentSeconds() != null) {
      joiner.add(String.format(Locale.ROOT, "%stimeSpentSeconds%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimeSpentSeconds()))));
    }

    return joiner.toString();
  }
}

