/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1bc87d9c91847a6f215496c203268482a08e6f70
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.jira.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.kestra.plugin.jira.client.invoker.ApiClient;
/**
 * The details of the preview workflow request.
 */
@JsonPropertyOrder({
  WorkflowPreviewRequest.JSON_PROPERTY_ISSUE_TYPE_IDS,
  WorkflowPreviewRequest.JSON_PROPERTY_PROJECT_ID,
  WorkflowPreviewRequest.JSON_PROPERTY_WORKFLOW_IDS,
  WorkflowPreviewRequest.JSON_PROPERTY_WORKFLOW_NAMES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class WorkflowPreviewRequest {
  public static final String JSON_PROPERTY_ISSUE_TYPE_IDS = "issueTypeIds";
  @javax.annotation.Nullable
  private List<String> issueTypeIds = new ArrayList<>();

  public static final String JSON_PROPERTY_PROJECT_ID = "projectId";
  @javax.annotation.Nonnull
  private String projectId;

  public static final String JSON_PROPERTY_WORKFLOW_IDS = "workflowIds";
  @javax.annotation.Nullable
  private List<String> workflowIds = new ArrayList<>();

  public static final String JSON_PROPERTY_WORKFLOW_NAMES = "workflowNames";
  @javax.annotation.Nullable
  private List<String> workflowNames = new ArrayList<>();

  public WorkflowPreviewRequest() { 
  }

  public WorkflowPreviewRequest issueTypeIds(@javax.annotation.Nullable List<String> issueTypeIds) {
    this.issueTypeIds = issueTypeIds;
    return this;
  }

  public WorkflowPreviewRequest addIssueTypeIdsItem(String issueTypeIdsItem) {
    if (this.issueTypeIds == null) {
      this.issueTypeIds = new ArrayList<>();
    }
    this.issueTypeIds.add(issueTypeIdsItem);
    return this;
  }

  /**
   * The list of issue type IDs. At most 25 issue type IDs can be specified.
   * @return issueTypeIds
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ISSUE_TYPE_IDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getIssueTypeIds() {
    return issueTypeIds;
  }


  @JsonProperty(value = JSON_PROPERTY_ISSUE_TYPE_IDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssueTypeIds(@javax.annotation.Nullable List<String> issueTypeIds) {
    this.issueTypeIds = issueTypeIds;
  }


  public WorkflowPreviewRequest projectId(@javax.annotation.Nonnull String projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * The projectId parameter is required and will be used for permission checks. In addition, you must supply at least one of the following lookup terms: *workflowNames*, *workflowIds*, or *issueTypeIds*. The specified workflows must be associated with the given project.
   * @return projectId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getProjectId() {
    return projectId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProjectId(@javax.annotation.Nonnull String projectId) {
    this.projectId = projectId;
  }


  public WorkflowPreviewRequest workflowIds(@javax.annotation.Nullable List<String> workflowIds) {
    this.workflowIds = workflowIds;
    return this;
  }

  public WorkflowPreviewRequest addWorkflowIdsItem(String workflowIdsItem) {
    if (this.workflowIds == null) {
      this.workflowIds = new ArrayList<>();
    }
    this.workflowIds.add(workflowIdsItem);
    return this;
  }

  /**
   * The list of workflow IDs to be returned. At most 25 workflow IDs can be specified.
   * @return workflowIds
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WORKFLOW_IDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getWorkflowIds() {
    return workflowIds;
  }


  @JsonProperty(value = JSON_PROPERTY_WORKFLOW_IDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWorkflowIds(@javax.annotation.Nullable List<String> workflowIds) {
    this.workflowIds = workflowIds;
  }


  public WorkflowPreviewRequest workflowNames(@javax.annotation.Nullable List<String> workflowNames) {
    this.workflowNames = workflowNames;
    return this;
  }

  public WorkflowPreviewRequest addWorkflowNamesItem(String workflowNamesItem) {
    if (this.workflowNames == null) {
      this.workflowNames = new ArrayList<>();
    }
    this.workflowNames.add(workflowNamesItem);
    return this;
  }

  /**
   * The list of workflow names to be returned. At most 25 workflow names can be specified.
   * @return workflowNames
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WORKFLOW_NAMES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getWorkflowNames() {
    return workflowNames;
  }


  @JsonProperty(value = JSON_PROPERTY_WORKFLOW_NAMES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWorkflowNames(@javax.annotation.Nullable List<String> workflowNames) {
    this.workflowNames = workflowNames;
  }


  /**
   * Return true if this WorkflowPreviewRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowPreviewRequest workflowPreviewRequest = (WorkflowPreviewRequest) o;
    return Objects.equals(this.issueTypeIds, workflowPreviewRequest.issueTypeIds) &&
        Objects.equals(this.projectId, workflowPreviewRequest.projectId) &&
        Objects.equals(this.workflowIds, workflowPreviewRequest.workflowIds) &&
        Objects.equals(this.workflowNames, workflowPreviewRequest.workflowNames);
  }

  @Override
  public int hashCode() {
    return Objects.hash(issueTypeIds, projectId, workflowIds, workflowNames);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowPreviewRequest {\n");
    sb.append("    issueTypeIds: ").append(toIndentedString(issueTypeIds)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    workflowIds: ").append(toIndentedString(workflowIds)).append("\n");
    sb.append("    workflowNames: ").append(toIndentedString(workflowNames)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `issueTypeIds` to the URL query string
    if (getIssueTypeIds() != null) {
      for (int i = 0; i < getIssueTypeIds().size(); i++) {
        joiner.add(String.format(Locale.ROOT, "%sissueTypeIds%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getIssueTypeIds().get(i)))));
      }
    }

    // add `projectId` to the URL query string
    if (getProjectId() != null) {
      joiner.add(String.format(Locale.ROOT, "%sprojectId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProjectId()))));
    }

    // add `workflowIds` to the URL query string
    if (getWorkflowIds() != null) {
      for (int i = 0; i < getWorkflowIds().size(); i++) {
        joiner.add(String.format(Locale.ROOT, "%sworkflowIds%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getWorkflowIds().get(i)))));
      }
    }

    // add `workflowNames` to the URL query string
    if (getWorkflowNames() != null) {
      for (int i = 0; i < getWorkflowNames().size(); i++) {
        joiner.add(String.format(Locale.ROOT, "%sworkflowNames%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getWorkflowNames().get(i)))));
      }
    }

    return joiner.toString();
  }
}

