/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1bc87d9c91847a6f215496c203268482a08e6f70
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.jira.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.kestra.plugin.jira.client.invoker.ApiClient;
/**
 * Properties that identify a workflow.
 */
@JsonPropertyOrder({
  WorkflowId.JSON_PROPERTY_DRAFT,
  WorkflowId.JSON_PROPERTY_NAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class WorkflowId {
  public static final String JSON_PROPERTY_DRAFT = "draft";
  @javax.annotation.Nonnull
  private Boolean draft;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public WorkflowId() { 
  }

  public WorkflowId draft(@javax.annotation.Nonnull Boolean draft) {
    this.draft = draft;
    return this;
  }

  /**
   * Whether the workflow is in the draft state.
   * @return draft
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DRAFT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getDraft() {
    return draft;
  }


  @JsonProperty(value = JSON_PROPERTY_DRAFT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDraft(@javax.annotation.Nonnull Boolean draft) {
    this.draft = draft;
  }


  public WorkflowId name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * The name of the workflow.
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  /**
   * Return true if this WorkflowId object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowId workflowId = (WorkflowId) o;
    return Objects.equals(this.draft, workflowId.draft) &&
        Objects.equals(this.name, workflowId.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(draft, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowId {\n");
    sb.append("    draft: ").append(toIndentedString(draft)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `draft` to the URL query string
    if (getDraft() != null) {
      joiner.add(String.format(Locale.ROOT, "%sdraft%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDraft()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    return joiner.toString();
  }
}

