/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1bc87d9c91847a6f215496c203268482a08e6f70
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.jira.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.kestra.plugin.jira.client.model.WorkflowCompoundCondition;
import io.kestra.plugin.jira.client.model.WorkflowSimpleCondition;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.Locale;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import io.kestra.plugin.jira.client.invoker.ApiClient;
import io.kestra.plugin.jira.client.invoker.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
@JsonDeserialize(using = WorkflowCondition.WorkflowConditionDeserializer.class)
@JsonSerialize(using = WorkflowCondition.WorkflowConditionSerializer.class)
public class WorkflowCondition extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(WorkflowCondition.class.getName());

    public static class WorkflowConditionSerializer extends StdSerializer<WorkflowCondition> {
        public WorkflowConditionSerializer(Class<WorkflowCondition> t) {
            super(t);
        }

        public WorkflowConditionSerializer() {
            this(null);
        }

        @Override
        public void serialize(WorkflowCondition value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class WorkflowConditionDeserializer extends StdDeserializer<WorkflowCondition> {
        public WorkflowConditionDeserializer() {
            this(WorkflowCondition.class);
        }

        public WorkflowConditionDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public WorkflowCondition deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize WorkflowCompoundCondition
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (WorkflowCompoundCondition.class.equals(Integer.class) || WorkflowCompoundCondition.class.equals(Long.class) || WorkflowCompoundCondition.class.equals(Float.class) || WorkflowCompoundCondition.class.equals(Double.class) || WorkflowCompoundCondition.class.equals(Boolean.class) || WorkflowCompoundCondition.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((WorkflowCompoundCondition.class.equals(Integer.class) || WorkflowCompoundCondition.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((WorkflowCompoundCondition.class.equals(Float.class) || WorkflowCompoundCondition.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (WorkflowCompoundCondition.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (WorkflowCompoundCondition.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(WorkflowCompoundCondition.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'WorkflowCompoundCondition'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'WorkflowCompoundCondition'", e);
            }

            // deserialize WorkflowSimpleCondition
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (WorkflowSimpleCondition.class.equals(Integer.class) || WorkflowSimpleCondition.class.equals(Long.class) || WorkflowSimpleCondition.class.equals(Float.class) || WorkflowSimpleCondition.class.equals(Double.class) || WorkflowSimpleCondition.class.equals(Boolean.class) || WorkflowSimpleCondition.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((WorkflowSimpleCondition.class.equals(Integer.class) || WorkflowSimpleCondition.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((WorkflowSimpleCondition.class.equals(Float.class) || WorkflowSimpleCondition.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (WorkflowSimpleCondition.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (WorkflowSimpleCondition.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(WorkflowSimpleCondition.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'WorkflowSimpleCondition'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'WorkflowSimpleCondition'", e);
            }

            if (match == 1) {
                WorkflowCondition ret = new WorkflowCondition();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format(Locale.ROOT, "Failed deserialization for WorkflowCondition: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public WorkflowCondition getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "WorkflowCondition cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public WorkflowCondition() {
        super("oneOf", Boolean.FALSE);
    }

    public WorkflowCondition(WorkflowCompoundCondition o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public WorkflowCondition(WorkflowSimpleCondition o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("WorkflowCompoundCondition", WorkflowCompoundCondition.class);
        schemas.put("WorkflowSimpleCondition", WorkflowSimpleCondition.class);
        JSON.registerDescendants(WorkflowCondition.class, Collections.unmodifiableMap(schemas));
        // Initialize and register the discriminator mappings.
        Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
        mappings.put("compound", WorkflowCompoundCondition.class);
        mappings.put("simple", WorkflowSimpleCondition.class);
        mappings.put("WorkflowCondition", WorkflowCondition.class);
        JSON.registerDiscriminator(WorkflowCondition.class, "nodeType", mappings);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return WorkflowCondition.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * WorkflowCompoundCondition, WorkflowSimpleCondition
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(WorkflowCompoundCondition.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(WorkflowSimpleCondition.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be WorkflowCompoundCondition, WorkflowSimpleCondition");
    }

    /**
     * Get the actual instance, which can be the following:
     * WorkflowCompoundCondition, WorkflowSimpleCondition
     *
     * @return The actual instance (WorkflowCompoundCondition, WorkflowSimpleCondition)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `WorkflowCompoundCondition`. If the actual instance is not `WorkflowCompoundCondition`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `WorkflowCompoundCondition`
     * @throws ClassCastException if the instance is not `WorkflowCompoundCondition`
     */
    public WorkflowCompoundCondition getWorkflowCompoundCondition() throws ClassCastException {
        return (WorkflowCompoundCondition)super.getActualInstance();
    }

    /**
     * Get the actual instance of `WorkflowSimpleCondition`. If the actual instance is not `WorkflowSimpleCondition`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `WorkflowSimpleCondition`
     * @throws ClassCastException if the instance is not `WorkflowSimpleCondition`
     */
    public WorkflowSimpleCondition getWorkflowSimpleCondition() throws ClassCastException {
        return (WorkflowSimpleCondition)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof WorkflowSimpleCondition) {
        if (getActualInstance() != null) {
          joiner.add(((WorkflowSimpleCondition)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof WorkflowCompoundCondition) {
        if (getActualInstance() != null) {
          joiner.add(((WorkflowCompoundCondition)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

