/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1bc87d9c91847a6f215496c203268482a08e6f70
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.kestra.plugin.atlassian_jira.client.api;

import com.google.gson.reflect.TypeToken;

import io.kestra.plugin.atlassian_jira.client.invoker.ApiCallback;
import io.kestra.plugin.atlassian_jira.client.invoker.ApiClient;
import io.kestra.plugin.atlassian_jira.client.invoker.ApiException;
import io.kestra.plugin.atlassian_jira.client.invoker.ApiResponse;
import io.kestra.plugin.atlassian_jira.client.invoker.Configuration;
import io.kestra.plugin.atlassian_jira.client.invoker.Pair;
import io.kestra.plugin.atlassian_jira.client.invoker.ProgressRequestBody;
import io.kestra.plugin.atlassian_jira.client.invoker.ProgressResponseBody;
import io.kestra.plugin.atlassian_jira.client.model.ContainerForProjectFeatures;
import io.kestra.plugin.atlassian_jira.client.model.ProjectFeatureState;

import java.io.IOException;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ProjectFeaturesApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ProjectFeaturesApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ProjectFeaturesApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getFeaturesForProject
     * 
     * @param projectIdOrKey The ID or (case-sensitive) key of the project.
     *                       (required)
     * @param _callback      Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     *                        <table border="1">
     *                        <caption>Response Details</caption>
     *                        <tr>
     *                        <td>Status Code</td>
     *                        <td>Description</td>
     *                        <td>Response Headers</td>
     *                        </tr>
     *                        <tr>
     *                        <td>200</td>
     *                        <td>Returned if the request is successful.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>400</td>
     *                        <td>Returned if the request is not valid.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>401</td>
     *                        <td>Returned if the authentication credentials are
     *                        incorrect or missing.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>403</td>
     *                        <td>Returned if the user does not have the required
     *                        permissions.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>404</td>
     *                        <td>Returned if the project is not found.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        </table>
     */
    public okhttp3.Call getFeaturesForProjectCall(@javax.annotation.Nonnull String projectIdOrKey,
            final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/rest/api/3/project/{projectIdOrKey}/features"
                .replace("{" + "projectIdOrKey" + "}", localVarApiClient.escapeString(projectIdOrKey.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
                "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "OAuth2", "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams,
                localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams,
                localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getFeaturesForProjectValidateBeforeCall(@javax.annotation.Nonnull String projectIdOrKey,
            final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectIdOrKey' is set
        if (projectIdOrKey == null) {
            throw new ApiException(
                    "Missing the required parameter 'projectIdOrKey' when calling getFeaturesForProject(Async)");
        }

        return getFeaturesForProjectCall(projectIdOrKey, _callback);

    }

    /**
     * Get project features
     * Returns the list of features for a project.
     * 
     * @param projectIdOrKey The ID or (case-sensitive) key of the project.
     *                       (required)
     * @return ContainerForProjectFeatures
     * @throws ApiException If fail to call the API, e.g. server error or cannot
     *                      deserialize the response body
     * @http.response.details
     *                        <table border="1">
     *                        <caption>Response Details</caption>
     *                        <tr>
     *                        <td>Status Code</td>
     *                        <td>Description</td>
     *                        <td>Response Headers</td>
     *                        </tr>
     *                        <tr>
     *                        <td>200</td>
     *                        <td>Returned if the request is successful.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>400</td>
     *                        <td>Returned if the request is not valid.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>401</td>
     *                        <td>Returned if the authentication credentials are
     *                        incorrect or missing.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>403</td>
     *                        <td>Returned if the user does not have the required
     *                        permissions.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>404</td>
     *                        <td>Returned if the project is not found.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        </table>
     */
    public ContainerForProjectFeatures getFeaturesForProject(@javax.annotation.Nonnull String projectIdOrKey)
            throws ApiException {
        ApiResponse<ContainerForProjectFeatures> localVarResp = getFeaturesForProjectWithHttpInfo(projectIdOrKey);
        return localVarResp.getData();
    }

    /**
     * Get project features
     * Returns the list of features for a project.
     * 
     * @param projectIdOrKey The ID or (case-sensitive) key of the project.
     *                       (required)
     * @return ApiResponse&lt;ContainerForProjectFeatures&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot
     *                      deserialize the response body
     * @http.response.details
     *                        <table border="1">
     *                        <caption>Response Details</caption>
     *                        <tr>
     *                        <td>Status Code</td>
     *                        <td>Description</td>
     *                        <td>Response Headers</td>
     *                        </tr>
     *                        <tr>
     *                        <td>200</td>
     *                        <td>Returned if the request is successful.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>400</td>
     *                        <td>Returned if the request is not valid.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>401</td>
     *                        <td>Returned if the authentication credentials are
     *                        incorrect or missing.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>403</td>
     *                        <td>Returned if the user does not have the required
     *                        permissions.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>404</td>
     *                        <td>Returned if the project is not found.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        </table>
     */
    public ApiResponse<ContainerForProjectFeatures> getFeaturesForProjectWithHttpInfo(
            @javax.annotation.Nonnull String projectIdOrKey) throws ApiException {
        okhttp3.Call localVarCall = getFeaturesForProjectValidateBeforeCall(projectIdOrKey, null);
        Type localVarReturnType = new TypeToken<ContainerForProjectFeatures>() {
        }.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get project features (asynchronously)
     * Returns the list of features for a project.
     * 
     * @param projectIdOrKey The ID or (case-sensitive) key of the project.
     *                       (required)
     * @param _callback      The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the
     *                      request body object
     * @http.response.details
     *                        <table border="1">
     *                        <caption>Response Details</caption>
     *                        <tr>
     *                        <td>Status Code</td>
     *                        <td>Description</td>
     *                        <td>Response Headers</td>
     *                        </tr>
     *                        <tr>
     *                        <td>200</td>
     *                        <td>Returned if the request is successful.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>400</td>
     *                        <td>Returned if the request is not valid.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>401</td>
     *                        <td>Returned if the authentication credentials are
     *                        incorrect or missing.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>403</td>
     *                        <td>Returned if the user does not have the required
     *                        permissions.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>404</td>
     *                        <td>Returned if the project is not found.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        </table>
     */
    public okhttp3.Call getFeaturesForProjectAsync(@javax.annotation.Nonnull String projectIdOrKey,
            final ApiCallback<ContainerForProjectFeatures> _callback) throws ApiException {

        okhttp3.Call localVarCall = getFeaturesForProjectValidateBeforeCall(projectIdOrKey, _callback);
        Type localVarReturnType = new TypeToken<ContainerForProjectFeatures>() {
        }.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    /**
     * Build call for toggleFeatureForProject
     * 
     * @param projectIdOrKey      The ID or (case-sensitive) key of the project.
     *                            (required)
     * @param featureKey          The key of the feature. (required)
     * @param projectFeatureState Details of the feature state change. (required)
     * @param _callback           Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     *                        <table border="1">
     *                        <caption>Response Details</caption>
     *                        <tr>
     *                        <td>Status Code</td>
     *                        <td>Description</td>
     *                        <td>Response Headers</td>
     *                        </tr>
     *                        <tr>
     *                        <td>200</td>
     *                        <td>Returned if the request is successful.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>400</td>
     *                        <td>Returned if the request is not valid.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>401</td>
     *                        <td>Returned if the authentication credentials are
     *                        incorrect or missing.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>403</td>
     *                        <td>Returned if the user does not have the required
     *                        permissions.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>404</td>
     *                        <td>Returned if the project or project feature is not
     *                        found.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        </table>
     */
    public okhttp3.Call toggleFeatureForProjectCall(@javax.annotation.Nonnull String projectIdOrKey,
            @javax.annotation.Nonnull String featureKey,
            @javax.annotation.Nonnull ProjectFeatureState projectFeatureState, final ApiCallback _callback)
            throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = projectFeatureState;

        // create path and map variables
        String localVarPath = "/rest/api/3/project/{projectIdOrKey}/features/{featureKey}"
                .replace("{" + "projectIdOrKey" + "}", localVarApiClient.escapeString(projectIdOrKey.toString()))
                .replace("{" + "featureKey" + "}", localVarApiClient.escapeString(featureKey.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
                "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
                "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "OAuth2", "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams,
                localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams,
                localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call toggleFeatureForProjectValidateBeforeCall(@javax.annotation.Nonnull String projectIdOrKey,
            @javax.annotation.Nonnull String featureKey,
            @javax.annotation.Nonnull ProjectFeatureState projectFeatureState, final ApiCallback _callback)
            throws ApiException {
        // verify the required parameter 'projectIdOrKey' is set
        if (projectIdOrKey == null) {
            throw new ApiException(
                    "Missing the required parameter 'projectIdOrKey' when calling toggleFeatureForProject(Async)");
        }

        // verify the required parameter 'featureKey' is set
        if (featureKey == null) {
            throw new ApiException(
                    "Missing the required parameter 'featureKey' when calling toggleFeatureForProject(Async)");
        }

        // verify the required parameter 'projectFeatureState' is set
        if (projectFeatureState == null) {
            throw new ApiException(
                    "Missing the required parameter 'projectFeatureState' when calling toggleFeatureForProject(Async)");
        }

        return toggleFeatureForProjectCall(projectIdOrKey, featureKey, projectFeatureState, _callback);

    }

    /**
     * Set project feature state
     * Sets the state of a project feature.
     * 
     * @param projectIdOrKey      The ID or (case-sensitive) key of the project.
     *                            (required)
     * @param featureKey          The key of the feature. (required)
     * @param projectFeatureState Details of the feature state change. (required)
     * @return ContainerForProjectFeatures
     * @throws ApiException If fail to call the API, e.g. server error or cannot
     *                      deserialize the response body
     * @http.response.details
     *                        <table border="1">
     *                        <caption>Response Details</caption>
     *                        <tr>
     *                        <td>Status Code</td>
     *                        <td>Description</td>
     *                        <td>Response Headers</td>
     *                        </tr>
     *                        <tr>
     *                        <td>200</td>
     *                        <td>Returned if the request is successful.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>400</td>
     *                        <td>Returned if the request is not valid.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>401</td>
     *                        <td>Returned if the authentication credentials are
     *                        incorrect or missing.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>403</td>
     *                        <td>Returned if the user does not have the required
     *                        permissions.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>404</td>
     *                        <td>Returned if the project or project feature is not
     *                        found.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        </table>
     */
    public ContainerForProjectFeatures toggleFeatureForProject(@javax.annotation.Nonnull String projectIdOrKey,
            @javax.annotation.Nonnull String featureKey,
            @javax.annotation.Nonnull ProjectFeatureState projectFeatureState) throws ApiException {
        ApiResponse<ContainerForProjectFeatures> localVarResp = toggleFeatureForProjectWithHttpInfo(projectIdOrKey,
                featureKey, projectFeatureState);
        return localVarResp.getData();
    }

    /**
     * Set project feature state
     * Sets the state of a project feature.
     * 
     * @param projectIdOrKey      The ID or (case-sensitive) key of the project.
     *                            (required)
     * @param featureKey          The key of the feature. (required)
     * @param projectFeatureState Details of the feature state change. (required)
     * @return ApiResponse&lt;ContainerForProjectFeatures&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot
     *                      deserialize the response body
     * @http.response.details
     *                        <table border="1">
     *                        <caption>Response Details</caption>
     *                        <tr>
     *                        <td>Status Code</td>
     *                        <td>Description</td>
     *                        <td>Response Headers</td>
     *                        </tr>
     *                        <tr>
     *                        <td>200</td>
     *                        <td>Returned if the request is successful.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>400</td>
     *                        <td>Returned if the request is not valid.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>401</td>
     *                        <td>Returned if the authentication credentials are
     *                        incorrect or missing.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>403</td>
     *                        <td>Returned if the user does not have the required
     *                        permissions.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>404</td>
     *                        <td>Returned if the project or project feature is not
     *                        found.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        </table>
     */
    public ApiResponse<ContainerForProjectFeatures> toggleFeatureForProjectWithHttpInfo(
            @javax.annotation.Nonnull String projectIdOrKey, @javax.annotation.Nonnull String featureKey,
            @javax.annotation.Nonnull ProjectFeatureState projectFeatureState) throws ApiException {
        okhttp3.Call localVarCall = toggleFeatureForProjectValidateBeforeCall(projectIdOrKey, featureKey,
                projectFeatureState, null);
        Type localVarReturnType = new TypeToken<ContainerForProjectFeatures>() {
        }.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Set project feature state (asynchronously)
     * Sets the state of a project feature.
     * 
     * @param projectIdOrKey      The ID or (case-sensitive) key of the project.
     *                            (required)
     * @param featureKey          The key of the feature. (required)
     * @param projectFeatureState Details of the feature state change. (required)
     * @param _callback           The callback to be executed when the API call
     *                            finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the
     *                      request body object
     * @http.response.details
     *                        <table border="1">
     *                        <caption>Response Details</caption>
     *                        <tr>
     *                        <td>Status Code</td>
     *                        <td>Description</td>
     *                        <td>Response Headers</td>
     *                        </tr>
     *                        <tr>
     *                        <td>200</td>
     *                        <td>Returned if the request is successful.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>400</td>
     *                        <td>Returned if the request is not valid.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>401</td>
     *                        <td>Returned if the authentication credentials are
     *                        incorrect or missing.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>403</td>
     *                        <td>Returned if the user does not have the required
     *                        permissions.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        <tr>
     *                        <td>404</td>
     *                        <td>Returned if the project or project feature is not
     *                        found.</td>
     *                        <td>-</td>
     *                        </tr>
     *                        </table>
     */
    public okhttp3.Call toggleFeatureForProjectAsync(@javax.annotation.Nonnull String projectIdOrKey,
            @javax.annotation.Nonnull String featureKey,
            @javax.annotation.Nonnull ProjectFeatureState projectFeatureState,
            final ApiCallback<ContainerForProjectFeatures> _callback) throws ApiException {

        okhttp3.Call localVarCall = toggleFeatureForProjectValidateBeforeCall(projectIdOrKey, featureKey,
                projectFeatureState, _callback);
        Type localVarReturnType = new TypeToken<ContainerForProjectFeatures>() {
        }.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
