/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1bc87d9c91847a6f215496c203268482a08e6f70
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.kestra.plugin.jira.client.api;

import io.kestra.plugin.jira.client.invoker.ApiClient;
import io.kestra.plugin.jira.client.invoker.ApiException;
import io.kestra.plugin.jira.client.invoker.ApiResponse;
import io.kestra.plugin.jira.client.invoker.Configuration;
import io.kestra.plugin.jira.client.invoker.Pair;

import io.kestra.plugin.jira.client.model.AutoCompleteSuggestions;
import io.kestra.plugin.jira.client.model.ConvertedJQLQueries;
import io.kestra.plugin.jira.client.model.ErrorCollection;
import io.kestra.plugin.jira.client.model.JQLPersonalDataMigrationRequest;
import io.kestra.plugin.jira.client.model.JQLReferenceData;
import io.kestra.plugin.jira.client.model.JqlQueriesToParse;
import io.kestra.plugin.jira.client.model.JqlQueriesToSanitize;
import io.kestra.plugin.jira.client.model.ParsedJqlQueries;
import io.kestra.plugin.jira.client.model.SanitizedJqlQueries;
import io.kestra.plugin.jira.client.model.SearchAutoCompleteFilter;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class JqlApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public JqlApi() {
    this(Configuration.getDefaultApiClient());
  }

  public JqlApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response) throws ApiException {
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(response.body(), file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Get field reference data (GET)
   * Returns reference data for JQL searches. This is a downloadable version of the documentation provided in [Advanced searching - fields reference](https://confluence.atlassian.com/x/gwORLQ) and [Advanced searching - functions reference](https://confluence.atlassian.com/x/hgORLQ), along with a list of JQL-reserved words. Use this information to assist with the programmatic creation of JQL queries or the validation of queries built in a custom query builder.  To filter visible field details by project or collapse non-unique fields by field type then [Get field reference data (POST)](#api-rest-api-3-jql-autocompletedata-post) can be used.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** None.
   * @return JQLReferenceData
   * @throws ApiException if fails to make API call
   */
  public JQLReferenceData getAutoComplete() throws ApiException {
    return getAutoComplete(null);
  }

  /**
   * Get field reference data (GET)
   * Returns reference data for JQL searches. This is a downloadable version of the documentation provided in [Advanced searching - fields reference](https://confluence.atlassian.com/x/gwORLQ) and [Advanced searching - functions reference](https://confluence.atlassian.com/x/hgORLQ), along with a list of JQL-reserved words. Use this information to assist with the programmatic creation of JQL queries or the validation of queries built in a custom query builder.  To filter visible field details by project or collapse non-unique fields by field type then [Get field reference data (POST)](#api-rest-api-3-jql-autocompletedata-post) can be used.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** None.
   * @param headers Optional headers to include in the request
   * @return JQLReferenceData
   * @throws ApiException if fails to make API call
   */
  public JQLReferenceData getAutoComplete(Map<String, String> headers) throws ApiException {
    ApiResponse<JQLReferenceData> localVarResponse = getAutoCompleteWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * Get field reference data (GET)
   * Returns reference data for JQL searches. This is a downloadable version of the documentation provided in [Advanced searching - fields reference](https://confluence.atlassian.com/x/gwORLQ) and [Advanced searching - functions reference](https://confluence.atlassian.com/x/hgORLQ), along with a list of JQL-reserved words. Use this information to assist with the programmatic creation of JQL queries or the validation of queries built in a custom query builder.  To filter visible field details by project or collapse non-unique fields by field type then [Get field reference data (POST)](#api-rest-api-3-jql-autocompletedata-post) can be used.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** None.
   * @return ApiResponse&lt;JQLReferenceData&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<JQLReferenceData> getAutoCompleteWithHttpInfo() throws ApiException {
    return getAutoCompleteWithHttpInfo(null);
  }

  /**
   * Get field reference data (GET)
   * Returns reference data for JQL searches. This is a downloadable version of the documentation provided in [Advanced searching - fields reference](https://confluence.atlassian.com/x/gwORLQ) and [Advanced searching - functions reference](https://confluence.atlassian.com/x/hgORLQ), along with a list of JQL-reserved words. Use this information to assist with the programmatic creation of JQL queries or the validation of queries built in a custom query builder.  To filter visible field details by project or collapse non-unique fields by field type then [Get field reference data (POST)](#api-rest-api-3-jql-autocompletedata-post) can be used.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** None.
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;JQLReferenceData&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<JQLReferenceData> getAutoCompleteWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getAutoCompleteRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getAutoComplete", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<JQLReferenceData>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        JQLReferenceData responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<JQLReferenceData>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<JQLReferenceData>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getAutoCompleteRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/rest/api/3/jql/autocompletedata";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get field reference data (POST)
   * Returns reference data for JQL searches. This is a downloadable version of the documentation provided in [Advanced searching - fields reference](https://confluence.atlassian.com/x/gwORLQ) and [Advanced searching - functions reference](https://confluence.atlassian.com/x/hgORLQ), along with a list of JQL-reserved words. Use this information to assist with the programmatic creation of JQL queries or the validation of queries built in a custom query builder.  This operation can filter the custom fields returned by project. Invalid project IDs in &#x60;projectIds&#x60; are ignored. System fields are always returned.  It can also return the collapsed field for custom fields. Collapsed fields enable searches to be performed across all fields with the same name and of the same field type. For example, the collapsed field &#x60;Component - Component[Dropdown]&#x60; enables dropdown fields &#x60;Component - cf[10061]&#x60; and &#x60;Component - cf[10062]&#x60; to be searched simultaneously.  **[Permissions](#permissions) required:** None.
   * @param searchAutoCompleteFilter  (required)
   * @return JQLReferenceData
   * @throws ApiException if fails to make API call
   */
  public JQLReferenceData getAutoCompletePost(@javax.annotation.Nonnull SearchAutoCompleteFilter searchAutoCompleteFilter) throws ApiException {
    return getAutoCompletePost(searchAutoCompleteFilter, null);
  }

  /**
   * Get field reference data (POST)
   * Returns reference data for JQL searches. This is a downloadable version of the documentation provided in [Advanced searching - fields reference](https://confluence.atlassian.com/x/gwORLQ) and [Advanced searching - functions reference](https://confluence.atlassian.com/x/hgORLQ), along with a list of JQL-reserved words. Use this information to assist with the programmatic creation of JQL queries or the validation of queries built in a custom query builder.  This operation can filter the custom fields returned by project. Invalid project IDs in &#x60;projectIds&#x60; are ignored. System fields are always returned.  It can also return the collapsed field for custom fields. Collapsed fields enable searches to be performed across all fields with the same name and of the same field type. For example, the collapsed field &#x60;Component - Component[Dropdown]&#x60; enables dropdown fields &#x60;Component - cf[10061]&#x60; and &#x60;Component - cf[10062]&#x60; to be searched simultaneously.  **[Permissions](#permissions) required:** None.
   * @param searchAutoCompleteFilter  (required)
   * @param headers Optional headers to include in the request
   * @return JQLReferenceData
   * @throws ApiException if fails to make API call
   */
  public JQLReferenceData getAutoCompletePost(@javax.annotation.Nonnull SearchAutoCompleteFilter searchAutoCompleteFilter, Map<String, String> headers) throws ApiException {
    ApiResponse<JQLReferenceData> localVarResponse = getAutoCompletePostWithHttpInfo(searchAutoCompleteFilter, headers);
    return localVarResponse.getData();
  }

  /**
   * Get field reference data (POST)
   * Returns reference data for JQL searches. This is a downloadable version of the documentation provided in [Advanced searching - fields reference](https://confluence.atlassian.com/x/gwORLQ) and [Advanced searching - functions reference](https://confluence.atlassian.com/x/hgORLQ), along with a list of JQL-reserved words. Use this information to assist with the programmatic creation of JQL queries or the validation of queries built in a custom query builder.  This operation can filter the custom fields returned by project. Invalid project IDs in &#x60;projectIds&#x60; are ignored. System fields are always returned.  It can also return the collapsed field for custom fields. Collapsed fields enable searches to be performed across all fields with the same name and of the same field type. For example, the collapsed field &#x60;Component - Component[Dropdown]&#x60; enables dropdown fields &#x60;Component - cf[10061]&#x60; and &#x60;Component - cf[10062]&#x60; to be searched simultaneously.  **[Permissions](#permissions) required:** None.
   * @param searchAutoCompleteFilter  (required)
   * @return ApiResponse&lt;JQLReferenceData&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<JQLReferenceData> getAutoCompletePostWithHttpInfo(@javax.annotation.Nonnull SearchAutoCompleteFilter searchAutoCompleteFilter) throws ApiException {
    return getAutoCompletePostWithHttpInfo(searchAutoCompleteFilter, null);
  }

  /**
   * Get field reference data (POST)
   * Returns reference data for JQL searches. This is a downloadable version of the documentation provided in [Advanced searching - fields reference](https://confluence.atlassian.com/x/gwORLQ) and [Advanced searching - functions reference](https://confluence.atlassian.com/x/hgORLQ), along with a list of JQL-reserved words. Use this information to assist with the programmatic creation of JQL queries or the validation of queries built in a custom query builder.  This operation can filter the custom fields returned by project. Invalid project IDs in &#x60;projectIds&#x60; are ignored. System fields are always returned.  It can also return the collapsed field for custom fields. Collapsed fields enable searches to be performed across all fields with the same name and of the same field type. For example, the collapsed field &#x60;Component - Component[Dropdown]&#x60; enables dropdown fields &#x60;Component - cf[10061]&#x60; and &#x60;Component - cf[10062]&#x60; to be searched simultaneously.  **[Permissions](#permissions) required:** None.
   * @param searchAutoCompleteFilter  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;JQLReferenceData&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<JQLReferenceData> getAutoCompletePostWithHttpInfo(@javax.annotation.Nonnull SearchAutoCompleteFilter searchAutoCompleteFilter, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getAutoCompletePostRequestBuilder(searchAutoCompleteFilter, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getAutoCompletePost", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<JQLReferenceData>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        JQLReferenceData responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<JQLReferenceData>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<JQLReferenceData>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getAutoCompletePostRequestBuilder(@javax.annotation.Nonnull SearchAutoCompleteFilter searchAutoCompleteFilter, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'searchAutoCompleteFilter' is set
    if (searchAutoCompleteFilter == null) {
      throw new ApiException(400, "Missing the required parameter 'searchAutoCompleteFilter' when calling getAutoCompletePost");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/rest/api/3/jql/autocompletedata";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(searchAutoCompleteFilter);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get field auto complete suggestions
   * Returns the JQL search auto complete suggestions for a field.  Suggestions can be obtained by providing:   *  &#x60;fieldName&#x60; to get a list of all values for the field.  *  &#x60;fieldName&#x60; and &#x60;fieldValue&#x60; to get a list of values containing the text in &#x60;fieldValue&#x60;.  *  &#x60;fieldName&#x60; and &#x60;predicateName&#x60; to get a list of all predicate values for the field.  *  &#x60;fieldName&#x60;, &#x60;predicateName&#x60;, and &#x60;predicateValue&#x60; to get a list of predicate values containing the text in &#x60;predicateValue&#x60;.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** None.
   * @param fieldName The name of the field. (optional)
   * @param fieldValue The partial field item name entered by the user. (optional)
   * @param predicateName The name of the [ CHANGED operator predicate](https://confluence.atlassian.com/x/hQORLQ#Advancedsearching-operatorsreference-CHANGEDCHANGED) for which the suggestions are generated. The valid predicate operators are *by*, *from*, and *to*. (optional)
   * @param predicateValue The partial predicate item name entered by the user. (optional)
   * @return AutoCompleteSuggestions
   * @throws ApiException if fails to make API call
   */
  public AutoCompleteSuggestions getFieldAutoCompleteForQueryString(@javax.annotation.Nullable String fieldName, @javax.annotation.Nullable String fieldValue, @javax.annotation.Nullable String predicateName, @javax.annotation.Nullable String predicateValue) throws ApiException {
    return getFieldAutoCompleteForQueryString(fieldName, fieldValue, predicateName, predicateValue, null);
  }

  /**
   * Get field auto complete suggestions
   * Returns the JQL search auto complete suggestions for a field.  Suggestions can be obtained by providing:   *  &#x60;fieldName&#x60; to get a list of all values for the field.  *  &#x60;fieldName&#x60; and &#x60;fieldValue&#x60; to get a list of values containing the text in &#x60;fieldValue&#x60;.  *  &#x60;fieldName&#x60; and &#x60;predicateName&#x60; to get a list of all predicate values for the field.  *  &#x60;fieldName&#x60;, &#x60;predicateName&#x60;, and &#x60;predicateValue&#x60; to get a list of predicate values containing the text in &#x60;predicateValue&#x60;.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** None.
   * @param fieldName The name of the field. (optional)
   * @param fieldValue The partial field item name entered by the user. (optional)
   * @param predicateName The name of the [ CHANGED operator predicate](https://confluence.atlassian.com/x/hQORLQ#Advancedsearching-operatorsreference-CHANGEDCHANGED) for which the suggestions are generated. The valid predicate operators are *by*, *from*, and *to*. (optional)
   * @param predicateValue The partial predicate item name entered by the user. (optional)
   * @param headers Optional headers to include in the request
   * @return AutoCompleteSuggestions
   * @throws ApiException if fails to make API call
   */
  public AutoCompleteSuggestions getFieldAutoCompleteForQueryString(@javax.annotation.Nullable String fieldName, @javax.annotation.Nullable String fieldValue, @javax.annotation.Nullable String predicateName, @javax.annotation.Nullable String predicateValue, Map<String, String> headers) throws ApiException {
    ApiResponse<AutoCompleteSuggestions> localVarResponse = getFieldAutoCompleteForQueryStringWithHttpInfo(fieldName, fieldValue, predicateName, predicateValue, headers);
    return localVarResponse.getData();
  }

  /**
   * Get field auto complete suggestions
   * Returns the JQL search auto complete suggestions for a field.  Suggestions can be obtained by providing:   *  &#x60;fieldName&#x60; to get a list of all values for the field.  *  &#x60;fieldName&#x60; and &#x60;fieldValue&#x60; to get a list of values containing the text in &#x60;fieldValue&#x60;.  *  &#x60;fieldName&#x60; and &#x60;predicateName&#x60; to get a list of all predicate values for the field.  *  &#x60;fieldName&#x60;, &#x60;predicateName&#x60;, and &#x60;predicateValue&#x60; to get a list of predicate values containing the text in &#x60;predicateValue&#x60;.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** None.
   * @param fieldName The name of the field. (optional)
   * @param fieldValue The partial field item name entered by the user. (optional)
   * @param predicateName The name of the [ CHANGED operator predicate](https://confluence.atlassian.com/x/hQORLQ#Advancedsearching-operatorsreference-CHANGEDCHANGED) for which the suggestions are generated. The valid predicate operators are *by*, *from*, and *to*. (optional)
   * @param predicateValue The partial predicate item name entered by the user. (optional)
   * @return ApiResponse&lt;AutoCompleteSuggestions&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<AutoCompleteSuggestions> getFieldAutoCompleteForQueryStringWithHttpInfo(@javax.annotation.Nullable String fieldName, @javax.annotation.Nullable String fieldValue, @javax.annotation.Nullable String predicateName, @javax.annotation.Nullable String predicateValue) throws ApiException {
    return getFieldAutoCompleteForQueryStringWithHttpInfo(fieldName, fieldValue, predicateName, predicateValue, null);
  }

  /**
   * Get field auto complete suggestions
   * Returns the JQL search auto complete suggestions for a field.  Suggestions can be obtained by providing:   *  &#x60;fieldName&#x60; to get a list of all values for the field.  *  &#x60;fieldName&#x60; and &#x60;fieldValue&#x60; to get a list of values containing the text in &#x60;fieldValue&#x60;.  *  &#x60;fieldName&#x60; and &#x60;predicateName&#x60; to get a list of all predicate values for the field.  *  &#x60;fieldName&#x60;, &#x60;predicateName&#x60;, and &#x60;predicateValue&#x60; to get a list of predicate values containing the text in &#x60;predicateValue&#x60;.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** None.
   * @param fieldName The name of the field. (optional)
   * @param fieldValue The partial field item name entered by the user. (optional)
   * @param predicateName The name of the [ CHANGED operator predicate](https://confluence.atlassian.com/x/hQORLQ#Advancedsearching-operatorsreference-CHANGEDCHANGED) for which the suggestions are generated. The valid predicate operators are *by*, *from*, and *to*. (optional)
   * @param predicateValue The partial predicate item name entered by the user. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;AutoCompleteSuggestions&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<AutoCompleteSuggestions> getFieldAutoCompleteForQueryStringWithHttpInfo(@javax.annotation.Nullable String fieldName, @javax.annotation.Nullable String fieldValue, @javax.annotation.Nullable String predicateName, @javax.annotation.Nullable String predicateValue, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getFieldAutoCompleteForQueryStringRequestBuilder(fieldName, fieldValue, predicateName, predicateValue, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getFieldAutoCompleteForQueryString", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<AutoCompleteSuggestions>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        AutoCompleteSuggestions responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<AutoCompleteSuggestions>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<AutoCompleteSuggestions>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getFieldAutoCompleteForQueryStringRequestBuilder(@javax.annotation.Nullable String fieldName, @javax.annotation.Nullable String fieldValue, @javax.annotation.Nullable String predicateName, @javax.annotation.Nullable String predicateValue, Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/rest/api/3/jql/autocompletedata/suggestions";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "fieldName";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("fieldName", fieldName));
    localVarQueryParameterBaseName = "fieldValue";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("fieldValue", fieldValue));
    localVarQueryParameterBaseName = "predicateName";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("predicateName", predicateName));
    localVarQueryParameterBaseName = "predicateValue";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("predicateValue", predicateValue));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Convert user identifiers to account IDs in JQL queries
   * Converts one or more JQL queries with user identifiers (username or user key) to equivalent JQL queries with account IDs.  You may wish to use this operation if your system stores JQL queries and you want to make them GDPR-compliant. For more information about GDPR-related changes, see the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/).  **[Permissions](#permissions) required:** Permission to access Jira.
   * @param jqLPersonalDataMigrationRequest  (required)
   * @return ConvertedJQLQueries
   * @throws ApiException if fails to make API call
   */
  public ConvertedJQLQueries migrateQueries(@javax.annotation.Nonnull JQLPersonalDataMigrationRequest jqLPersonalDataMigrationRequest) throws ApiException {
    return migrateQueries(jqLPersonalDataMigrationRequest, null);
  }

  /**
   * Convert user identifiers to account IDs in JQL queries
   * Converts one or more JQL queries with user identifiers (username or user key) to equivalent JQL queries with account IDs.  You may wish to use this operation if your system stores JQL queries and you want to make them GDPR-compliant. For more information about GDPR-related changes, see the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/).  **[Permissions](#permissions) required:** Permission to access Jira.
   * @param jqLPersonalDataMigrationRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ConvertedJQLQueries
   * @throws ApiException if fails to make API call
   */
  public ConvertedJQLQueries migrateQueries(@javax.annotation.Nonnull JQLPersonalDataMigrationRequest jqLPersonalDataMigrationRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<ConvertedJQLQueries> localVarResponse = migrateQueriesWithHttpInfo(jqLPersonalDataMigrationRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Convert user identifiers to account IDs in JQL queries
   * Converts one or more JQL queries with user identifiers (username or user key) to equivalent JQL queries with account IDs.  You may wish to use this operation if your system stores JQL queries and you want to make them GDPR-compliant. For more information about GDPR-related changes, see the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/).  **[Permissions](#permissions) required:** Permission to access Jira.
   * @param jqLPersonalDataMigrationRequest  (required)
   * @return ApiResponse&lt;ConvertedJQLQueries&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ConvertedJQLQueries> migrateQueriesWithHttpInfo(@javax.annotation.Nonnull JQLPersonalDataMigrationRequest jqLPersonalDataMigrationRequest) throws ApiException {
    return migrateQueriesWithHttpInfo(jqLPersonalDataMigrationRequest, null);
  }

  /**
   * Convert user identifiers to account IDs in JQL queries
   * Converts one or more JQL queries with user identifiers (username or user key) to equivalent JQL queries with account IDs.  You may wish to use this operation if your system stores JQL queries and you want to make them GDPR-compliant. For more information about GDPR-related changes, see the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/).  **[Permissions](#permissions) required:** Permission to access Jira.
   * @param jqLPersonalDataMigrationRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ConvertedJQLQueries&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ConvertedJQLQueries> migrateQueriesWithHttpInfo(@javax.annotation.Nonnull JQLPersonalDataMigrationRequest jqLPersonalDataMigrationRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = migrateQueriesRequestBuilder(jqLPersonalDataMigrationRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("migrateQueries", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<ConvertedJQLQueries>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        ConvertedJQLQueries responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ConvertedJQLQueries>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<ConvertedJQLQueries>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder migrateQueriesRequestBuilder(@javax.annotation.Nonnull JQLPersonalDataMigrationRequest jqLPersonalDataMigrationRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'jqLPersonalDataMigrationRequest' is set
    if (jqLPersonalDataMigrationRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'jqLPersonalDataMigrationRequest' when calling migrateQueries");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/rest/api/3/jql/pdcleaner";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(jqLPersonalDataMigrationRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Parse JQL query
   * Parses and validates JQL queries.  Validation is performed in context of the current user.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** None.
   * @param validation How to validate the JQL query and treat the validation results. Validation options include:   *  &#x60;strict&#x60; Returns all errors. If validation fails, the query structure is not returned.  *  &#x60;warn&#x60; Returns all errors. If validation fails but the JQL query is correctly formed, the query structure is returned.  *  &#x60;none&#x60; No validation is performed. If JQL query is correctly formed, the query structure is returned. (required)
   * @param jqlQueriesToParse  (required)
   * @return ParsedJqlQueries
   * @throws ApiException if fails to make API call
   */
  public ParsedJqlQueries parseJqlQueries(@javax.annotation.Nonnull String validation, @javax.annotation.Nonnull JqlQueriesToParse jqlQueriesToParse) throws ApiException {
    return parseJqlQueries(validation, jqlQueriesToParse, null);
  }

  /**
   * Parse JQL query
   * Parses and validates JQL queries.  Validation is performed in context of the current user.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** None.
   * @param validation How to validate the JQL query and treat the validation results. Validation options include:   *  &#x60;strict&#x60; Returns all errors. If validation fails, the query structure is not returned.  *  &#x60;warn&#x60; Returns all errors. If validation fails but the JQL query is correctly formed, the query structure is returned.  *  &#x60;none&#x60; No validation is performed. If JQL query is correctly formed, the query structure is returned. (required)
   * @param jqlQueriesToParse  (required)
   * @param headers Optional headers to include in the request
   * @return ParsedJqlQueries
   * @throws ApiException if fails to make API call
   */
  public ParsedJqlQueries parseJqlQueries(@javax.annotation.Nonnull String validation, @javax.annotation.Nonnull JqlQueriesToParse jqlQueriesToParse, Map<String, String> headers) throws ApiException {
    ApiResponse<ParsedJqlQueries> localVarResponse = parseJqlQueriesWithHttpInfo(validation, jqlQueriesToParse, headers);
    return localVarResponse.getData();
  }

  /**
   * Parse JQL query
   * Parses and validates JQL queries.  Validation is performed in context of the current user.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** None.
   * @param validation How to validate the JQL query and treat the validation results. Validation options include:   *  &#x60;strict&#x60; Returns all errors. If validation fails, the query structure is not returned.  *  &#x60;warn&#x60; Returns all errors. If validation fails but the JQL query is correctly formed, the query structure is returned.  *  &#x60;none&#x60; No validation is performed. If JQL query is correctly formed, the query structure is returned. (required)
   * @param jqlQueriesToParse  (required)
   * @return ApiResponse&lt;ParsedJqlQueries&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ParsedJqlQueries> parseJqlQueriesWithHttpInfo(@javax.annotation.Nonnull String validation, @javax.annotation.Nonnull JqlQueriesToParse jqlQueriesToParse) throws ApiException {
    return parseJqlQueriesWithHttpInfo(validation, jqlQueriesToParse, null);
  }

  /**
   * Parse JQL query
   * Parses and validates JQL queries.  Validation is performed in context of the current user.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** None.
   * @param validation How to validate the JQL query and treat the validation results. Validation options include:   *  &#x60;strict&#x60; Returns all errors. If validation fails, the query structure is not returned.  *  &#x60;warn&#x60; Returns all errors. If validation fails but the JQL query is correctly formed, the query structure is returned.  *  &#x60;none&#x60; No validation is performed. If JQL query is correctly formed, the query structure is returned. (required)
   * @param jqlQueriesToParse  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ParsedJqlQueries&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ParsedJqlQueries> parseJqlQueriesWithHttpInfo(@javax.annotation.Nonnull String validation, @javax.annotation.Nonnull JqlQueriesToParse jqlQueriesToParse, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = parseJqlQueriesRequestBuilder(validation, jqlQueriesToParse, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("parseJqlQueries", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<ParsedJqlQueries>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        ParsedJqlQueries responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ParsedJqlQueries>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<ParsedJqlQueries>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder parseJqlQueriesRequestBuilder(@javax.annotation.Nonnull String validation, @javax.annotation.Nonnull JqlQueriesToParse jqlQueriesToParse, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'validation' is set
    if (validation == null) {
      throw new ApiException(400, "Missing the required parameter 'validation' when calling parseJqlQueries");
    }
    // verify the required parameter 'jqlQueriesToParse' is set
    if (jqlQueriesToParse == null) {
      throw new ApiException(400, "Missing the required parameter 'jqlQueriesToParse' when calling parseJqlQueries");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/rest/api/3/jql/parse";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "validation";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("validation", validation));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(jqlQueriesToParse);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Sanitize JQL queries
   * Sanitizes one or more JQL queries by converting readable details into IDs where a user doesn&#39;t have permission to view the entity.  For example, if the query contains the clause *project &#x3D; &#39;Secret project&#39;*, and a user does not have browse permission for the project \&quot;Secret project\&quot;, the sanitized query replaces the clause with *project &#x3D; 12345\&quot;* (where 12345 is the ID of the project). If a user has the required permission, the clause is not sanitized. If the account ID is null, sanitizing is performed for an anonymous user.  Note that sanitization doesn&#39;t make the queries GDPR-compliant, because it doesn&#39;t remove user identifiers (username or user key). If you need to make queries GDPR-compliant, use [Convert user identifiers to account IDs in JQL queries](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-jql/#api-rest-api-3-jql-sanitize-post).  Before sanitization each JQL query is parsed. The queries are returned in the same order that they were passed.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param jqlQueriesToSanitize  (required)
   * @return SanitizedJqlQueries
   * @throws ApiException if fails to make API call
   */
  public SanitizedJqlQueries sanitiseJqlQueries(@javax.annotation.Nonnull JqlQueriesToSanitize jqlQueriesToSanitize) throws ApiException {
    return sanitiseJqlQueries(jqlQueriesToSanitize, null);
  }

  /**
   * Sanitize JQL queries
   * Sanitizes one or more JQL queries by converting readable details into IDs where a user doesn&#39;t have permission to view the entity.  For example, if the query contains the clause *project &#x3D; &#39;Secret project&#39;*, and a user does not have browse permission for the project \&quot;Secret project\&quot;, the sanitized query replaces the clause with *project &#x3D; 12345\&quot;* (where 12345 is the ID of the project). If a user has the required permission, the clause is not sanitized. If the account ID is null, sanitizing is performed for an anonymous user.  Note that sanitization doesn&#39;t make the queries GDPR-compliant, because it doesn&#39;t remove user identifiers (username or user key). If you need to make queries GDPR-compliant, use [Convert user identifiers to account IDs in JQL queries](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-jql/#api-rest-api-3-jql-sanitize-post).  Before sanitization each JQL query is parsed. The queries are returned in the same order that they were passed.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param jqlQueriesToSanitize  (required)
   * @param headers Optional headers to include in the request
   * @return SanitizedJqlQueries
   * @throws ApiException if fails to make API call
   */
  public SanitizedJqlQueries sanitiseJqlQueries(@javax.annotation.Nonnull JqlQueriesToSanitize jqlQueriesToSanitize, Map<String, String> headers) throws ApiException {
    ApiResponse<SanitizedJqlQueries> localVarResponse = sanitiseJqlQueriesWithHttpInfo(jqlQueriesToSanitize, headers);
    return localVarResponse.getData();
  }

  /**
   * Sanitize JQL queries
   * Sanitizes one or more JQL queries by converting readable details into IDs where a user doesn&#39;t have permission to view the entity.  For example, if the query contains the clause *project &#x3D; &#39;Secret project&#39;*, and a user does not have browse permission for the project \&quot;Secret project\&quot;, the sanitized query replaces the clause with *project &#x3D; 12345\&quot;* (where 12345 is the ID of the project). If a user has the required permission, the clause is not sanitized. If the account ID is null, sanitizing is performed for an anonymous user.  Note that sanitization doesn&#39;t make the queries GDPR-compliant, because it doesn&#39;t remove user identifiers (username or user key). If you need to make queries GDPR-compliant, use [Convert user identifiers to account IDs in JQL queries](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-jql/#api-rest-api-3-jql-sanitize-post).  Before sanitization each JQL query is parsed. The queries are returned in the same order that they were passed.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param jqlQueriesToSanitize  (required)
   * @return ApiResponse&lt;SanitizedJqlQueries&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<SanitizedJqlQueries> sanitiseJqlQueriesWithHttpInfo(@javax.annotation.Nonnull JqlQueriesToSanitize jqlQueriesToSanitize) throws ApiException {
    return sanitiseJqlQueriesWithHttpInfo(jqlQueriesToSanitize, null);
  }

  /**
   * Sanitize JQL queries
   * Sanitizes one or more JQL queries by converting readable details into IDs where a user doesn&#39;t have permission to view the entity.  For example, if the query contains the clause *project &#x3D; &#39;Secret project&#39;*, and a user does not have browse permission for the project \&quot;Secret project\&quot;, the sanitized query replaces the clause with *project &#x3D; 12345\&quot;* (where 12345 is the ID of the project). If a user has the required permission, the clause is not sanitized. If the account ID is null, sanitizing is performed for an anonymous user.  Note that sanitization doesn&#39;t make the queries GDPR-compliant, because it doesn&#39;t remove user identifiers (username or user key). If you need to make queries GDPR-compliant, use [Convert user identifiers to account IDs in JQL queries](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-jql/#api-rest-api-3-jql-sanitize-post).  Before sanitization each JQL query is parsed. The queries are returned in the same order that they were passed.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param jqlQueriesToSanitize  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;SanitizedJqlQueries&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<SanitizedJqlQueries> sanitiseJqlQueriesWithHttpInfo(@javax.annotation.Nonnull JqlQueriesToSanitize jqlQueriesToSanitize, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = sanitiseJqlQueriesRequestBuilder(jqlQueriesToSanitize, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("sanitiseJqlQueries", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<SanitizedJqlQueries>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        SanitizedJqlQueries responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<SanitizedJqlQueries>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<SanitizedJqlQueries>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder sanitiseJqlQueriesRequestBuilder(@javax.annotation.Nonnull JqlQueriesToSanitize jqlQueriesToSanitize, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'jqlQueriesToSanitize' is set
    if (jqlQueriesToSanitize == null) {
      throw new ApiException(400, "Missing the required parameter 'jqlQueriesToSanitize' when calling sanitiseJqlQueries");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/rest/api/3/jql/sanitize";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(jqlQueriesToSanitize);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
