/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1bc87d9c91847a6f215496c203268482a08e6f70
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.kestra.plugin.jira.client.api;

import io.kestra.plugin.jira.client.invoker.ApiClient;
import io.kestra.plugin.jira.client.invoker.ApiException;
import io.kestra.plugin.jira.client.invoker.ApiResponse;
import io.kestra.plugin.jira.client.invoker.Configuration;
import io.kestra.plugin.jira.client.invoker.Pair;

import io.kestra.plugin.jira.client.model.UpdateDefaultProjectClassificationBean;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class ProjectClassificationLevelsApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public ProjectClassificationLevelsApi() {
    this(Configuration.getDefaultApiClient());
  }

  public ProjectClassificationLevelsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response) throws ApiException {
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(response.body(), file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Get the default data classification level of a project
   * Returns the default data classification for a project.  **[Permissions](#permissions) required:**   *  *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param projectIdOrKey The project ID or project key (case-sensitive). (required)
   * @return Object
   * @throws ApiException if fails to make API call
   */
  public Object getDefaultProjectClassification(@javax.annotation.Nonnull String projectIdOrKey) throws ApiException {
    return getDefaultProjectClassification(projectIdOrKey, null);
  }

  /**
   * Get the default data classification level of a project
   * Returns the default data classification for a project.  **[Permissions](#permissions) required:**   *  *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param projectIdOrKey The project ID or project key (case-sensitive). (required)
   * @param headers Optional headers to include in the request
   * @return Object
   * @throws ApiException if fails to make API call
   */
  public Object getDefaultProjectClassification(@javax.annotation.Nonnull String projectIdOrKey, Map<String, String> headers) throws ApiException {
    ApiResponse<Object> localVarResponse = getDefaultProjectClassificationWithHttpInfo(projectIdOrKey, headers);
    return localVarResponse.getData();
  }

  /**
   * Get the default data classification level of a project
   * Returns the default data classification for a project.  **[Permissions](#permissions) required:**   *  *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param projectIdOrKey The project ID or project key (case-sensitive). (required)
   * @return ApiResponse&lt;Object&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Object> getDefaultProjectClassificationWithHttpInfo(@javax.annotation.Nonnull String projectIdOrKey) throws ApiException {
    return getDefaultProjectClassificationWithHttpInfo(projectIdOrKey, null);
  }

  /**
   * Get the default data classification level of a project
   * Returns the default data classification for a project.  **[Permissions](#permissions) required:**   *  *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param projectIdOrKey The project ID or project key (case-sensitive). (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Object&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Object> getDefaultProjectClassificationWithHttpInfo(@javax.annotation.Nonnull String projectIdOrKey, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getDefaultProjectClassificationRequestBuilder(projectIdOrKey, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getDefaultProjectClassification", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<Object>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        Object responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Object>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<Object>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getDefaultProjectClassificationRequestBuilder(@javax.annotation.Nonnull String projectIdOrKey, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectIdOrKey' is set
    if (projectIdOrKey == null) {
      throw new ApiException(400, "Missing the required parameter 'projectIdOrKey' when calling getDefaultProjectClassification");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/rest/api/3/project/{projectIdOrKey}/classification-level/default"
        .replace("{projectIdOrKey}", ApiClient.urlEncode(projectIdOrKey.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Remove the default data classification level from a project
   * Remove the default data classification level for a project.  **[Permissions](#permissions) required:**   *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param projectIdOrKey The project ID or project key (case-sensitive). (required)
   * @return Object
   * @throws ApiException if fails to make API call
   */
  public Object removeDefaultProjectClassification(@javax.annotation.Nonnull String projectIdOrKey) throws ApiException {
    return removeDefaultProjectClassification(projectIdOrKey, null);
  }

  /**
   * Remove the default data classification level from a project
   * Remove the default data classification level for a project.  **[Permissions](#permissions) required:**   *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param projectIdOrKey The project ID or project key (case-sensitive). (required)
   * @param headers Optional headers to include in the request
   * @return Object
   * @throws ApiException if fails to make API call
   */
  public Object removeDefaultProjectClassification(@javax.annotation.Nonnull String projectIdOrKey, Map<String, String> headers) throws ApiException {
    ApiResponse<Object> localVarResponse = removeDefaultProjectClassificationWithHttpInfo(projectIdOrKey, headers);
    return localVarResponse.getData();
  }

  /**
   * Remove the default data classification level from a project
   * Remove the default data classification level for a project.  **[Permissions](#permissions) required:**   *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param projectIdOrKey The project ID or project key (case-sensitive). (required)
   * @return ApiResponse&lt;Object&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Object> removeDefaultProjectClassificationWithHttpInfo(@javax.annotation.Nonnull String projectIdOrKey) throws ApiException {
    return removeDefaultProjectClassificationWithHttpInfo(projectIdOrKey, null);
  }

  /**
   * Remove the default data classification level from a project
   * Remove the default data classification level for a project.  **[Permissions](#permissions) required:**   *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param projectIdOrKey The project ID or project key (case-sensitive). (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Object&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Object> removeDefaultProjectClassificationWithHttpInfo(@javax.annotation.Nonnull String projectIdOrKey, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = removeDefaultProjectClassificationRequestBuilder(projectIdOrKey, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("removeDefaultProjectClassification", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<Object>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        Object responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Object>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<Object>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder removeDefaultProjectClassificationRequestBuilder(@javax.annotation.Nonnull String projectIdOrKey, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectIdOrKey' is set
    if (projectIdOrKey == null) {
      throw new ApiException(400, "Missing the required parameter 'projectIdOrKey' when calling removeDefaultProjectClassification");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/rest/api/3/project/{projectIdOrKey}/classification-level/default"
        .replace("{projectIdOrKey}", ApiClient.urlEncode(projectIdOrKey.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Update the default data classification level of a project
   * Updates the default data classification level for a project.  **[Permissions](#permissions) required:**   *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param projectIdOrKey The project ID or project key (case-sensitive). (required)
   * @param updateDefaultProjectClassificationBean  (required)
   * @return Object
   * @throws ApiException if fails to make API call
   */
  public Object updateDefaultProjectClassification(@javax.annotation.Nonnull String projectIdOrKey, @javax.annotation.Nonnull UpdateDefaultProjectClassificationBean updateDefaultProjectClassificationBean) throws ApiException {
    return updateDefaultProjectClassification(projectIdOrKey, updateDefaultProjectClassificationBean, null);
  }

  /**
   * Update the default data classification level of a project
   * Updates the default data classification level for a project.  **[Permissions](#permissions) required:**   *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param projectIdOrKey The project ID or project key (case-sensitive). (required)
   * @param updateDefaultProjectClassificationBean  (required)
   * @param headers Optional headers to include in the request
   * @return Object
   * @throws ApiException if fails to make API call
   */
  public Object updateDefaultProjectClassification(@javax.annotation.Nonnull String projectIdOrKey, @javax.annotation.Nonnull UpdateDefaultProjectClassificationBean updateDefaultProjectClassificationBean, Map<String, String> headers) throws ApiException {
    ApiResponse<Object> localVarResponse = updateDefaultProjectClassificationWithHttpInfo(projectIdOrKey, updateDefaultProjectClassificationBean, headers);
    return localVarResponse.getData();
  }

  /**
   * Update the default data classification level of a project
   * Updates the default data classification level for a project.  **[Permissions](#permissions) required:**   *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param projectIdOrKey The project ID or project key (case-sensitive). (required)
   * @param updateDefaultProjectClassificationBean  (required)
   * @return ApiResponse&lt;Object&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Object> updateDefaultProjectClassificationWithHttpInfo(@javax.annotation.Nonnull String projectIdOrKey, @javax.annotation.Nonnull UpdateDefaultProjectClassificationBean updateDefaultProjectClassificationBean) throws ApiException {
    return updateDefaultProjectClassificationWithHttpInfo(projectIdOrKey, updateDefaultProjectClassificationBean, null);
  }

  /**
   * Update the default data classification level of a project
   * Updates the default data classification level for a project.  **[Permissions](#permissions) required:**   *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param projectIdOrKey The project ID or project key (case-sensitive). (required)
   * @param updateDefaultProjectClassificationBean  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Object&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Object> updateDefaultProjectClassificationWithHttpInfo(@javax.annotation.Nonnull String projectIdOrKey, @javax.annotation.Nonnull UpdateDefaultProjectClassificationBean updateDefaultProjectClassificationBean, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = updateDefaultProjectClassificationRequestBuilder(projectIdOrKey, updateDefaultProjectClassificationBean, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("updateDefaultProjectClassification", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<Object>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        Object responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Object>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<Object>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder updateDefaultProjectClassificationRequestBuilder(@javax.annotation.Nonnull String projectIdOrKey, @javax.annotation.Nonnull UpdateDefaultProjectClassificationBean updateDefaultProjectClassificationBean, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectIdOrKey' is set
    if (projectIdOrKey == null) {
      throw new ApiException(400, "Missing the required parameter 'projectIdOrKey' when calling updateDefaultProjectClassification");
    }
    // verify the required parameter 'updateDefaultProjectClassificationBean' is set
    if (updateDefaultProjectClassificationBean == null) {
      throw new ApiException(400, "Missing the required parameter 'updateDefaultProjectClassificationBean' when calling updateDefaultProjectClassification");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/rest/api/3/project/{projectIdOrKey}/classification-level/default"
        .replace("{projectIdOrKey}", ApiClient.urlEncode(projectIdOrKey.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(updateDefaultProjectClassificationBean);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
