/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1bc87d9c91847a6f215496c203268482a08e6f70
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.kestra.plugin.jira.client.api;

import io.kestra.plugin.jira.client.invoker.ApiClient;
import io.kestra.plugin.jira.client.invoker.ApiException;
import io.kestra.plugin.jira.client.invoker.ApiResponse;
import io.kestra.plugin.jira.client.invoker.Configuration;
import io.kestra.plugin.jira.client.invoker.Pair;

import io.kestra.plugin.jira.client.model.TimeTrackingConfiguration;
import io.kestra.plugin.jira.client.model.TimeTrackingProvider;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class TimeTrackingApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public TimeTrackingApi() {
    this(Configuration.getDefaultApiClient());
  }

  public TimeTrackingApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response) throws ApiException {
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(response.body(), file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Get all time tracking providers
   * Returns all time tracking providers. By default, Jira only has one time tracking provider: *JIRA provided time tracking*. However, you can install other time tracking providers via apps from the Atlassian Marketplace. For more information on time tracking providers, see the documentation for the [ Time Tracking Provider](https://developer.atlassian.com/cloud/jira/platform/modules/time-tracking-provider/) module.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @return List&lt;TimeTrackingProvider&gt;
   * @throws ApiException if fails to make API call
   */
  public List<TimeTrackingProvider> getAvailableTimeTrackingImplementations() throws ApiException {
    return getAvailableTimeTrackingImplementations(null);
  }

  /**
   * Get all time tracking providers
   * Returns all time tracking providers. By default, Jira only has one time tracking provider: *JIRA provided time tracking*. However, you can install other time tracking providers via apps from the Atlassian Marketplace. For more information on time tracking providers, see the documentation for the [ Time Tracking Provider](https://developer.atlassian.com/cloud/jira/platform/modules/time-tracking-provider/) module.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param headers Optional headers to include in the request
   * @return List&lt;TimeTrackingProvider&gt;
   * @throws ApiException if fails to make API call
   */
  public List<TimeTrackingProvider> getAvailableTimeTrackingImplementations(Map<String, String> headers) throws ApiException {
    ApiResponse<List<TimeTrackingProvider>> localVarResponse = getAvailableTimeTrackingImplementationsWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * Get all time tracking providers
   * Returns all time tracking providers. By default, Jira only has one time tracking provider: *JIRA provided time tracking*. However, you can install other time tracking providers via apps from the Atlassian Marketplace. For more information on time tracking providers, see the documentation for the [ Time Tracking Provider](https://developer.atlassian.com/cloud/jira/platform/modules/time-tracking-provider/) module.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @return ApiResponse&lt;List&lt;TimeTrackingProvider&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<TimeTrackingProvider>> getAvailableTimeTrackingImplementationsWithHttpInfo() throws ApiException {
    return getAvailableTimeTrackingImplementationsWithHttpInfo(null);
  }

  /**
   * Get all time tracking providers
   * Returns all time tracking providers. By default, Jira only has one time tracking provider: *JIRA provided time tracking*. However, you can install other time tracking providers via apps from the Atlassian Marketplace. For more information on time tracking providers, see the documentation for the [ Time Tracking Provider](https://developer.atlassian.com/cloud/jira/platform/modules/time-tracking-provider/) module.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;List&lt;TimeTrackingProvider&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<TimeTrackingProvider>> getAvailableTimeTrackingImplementationsWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getAvailableTimeTrackingImplementationsRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getAvailableTimeTrackingImplementations", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<List<TimeTrackingProvider>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        List<TimeTrackingProvider> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<TimeTrackingProvider>>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<List<TimeTrackingProvider>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getAvailableTimeTrackingImplementationsRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/rest/api/3/configuration/timetracking/list";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get selected time tracking provider
   * Returns the time tracking provider that is currently selected. Note that if time tracking is disabled, then a successful but empty response is returned.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @return TimeTrackingProvider
   * @throws ApiException if fails to make API call
   */
  public TimeTrackingProvider getSelectedTimeTrackingImplementation() throws ApiException {
    return getSelectedTimeTrackingImplementation(null);
  }

  /**
   * Get selected time tracking provider
   * Returns the time tracking provider that is currently selected. Note that if time tracking is disabled, then a successful but empty response is returned.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param headers Optional headers to include in the request
   * @return TimeTrackingProvider
   * @throws ApiException if fails to make API call
   */
  public TimeTrackingProvider getSelectedTimeTrackingImplementation(Map<String, String> headers) throws ApiException {
    ApiResponse<TimeTrackingProvider> localVarResponse = getSelectedTimeTrackingImplementationWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * Get selected time tracking provider
   * Returns the time tracking provider that is currently selected. Note that if time tracking is disabled, then a successful but empty response is returned.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @return ApiResponse&lt;TimeTrackingProvider&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TimeTrackingProvider> getSelectedTimeTrackingImplementationWithHttpInfo() throws ApiException {
    return getSelectedTimeTrackingImplementationWithHttpInfo(null);
  }

  /**
   * Get selected time tracking provider
   * Returns the time tracking provider that is currently selected. Note that if time tracking is disabled, then a successful but empty response is returned.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;TimeTrackingProvider&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TimeTrackingProvider> getSelectedTimeTrackingImplementationWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getSelectedTimeTrackingImplementationRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getSelectedTimeTrackingImplementation", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<TimeTrackingProvider>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        TimeTrackingProvider responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<TimeTrackingProvider>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<TimeTrackingProvider>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getSelectedTimeTrackingImplementationRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/rest/api/3/configuration/timetracking";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get time tracking settings
   * Returns the time tracking settings. This includes settings such as the time format, default time unit, and others. For more information, see [Configuring time tracking](https://confluence.atlassian.com/x/qoXKM).  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @return TimeTrackingConfiguration
   * @throws ApiException if fails to make API call
   */
  public TimeTrackingConfiguration getSharedTimeTrackingConfiguration() throws ApiException {
    return getSharedTimeTrackingConfiguration(null);
  }

  /**
   * Get time tracking settings
   * Returns the time tracking settings. This includes settings such as the time format, default time unit, and others. For more information, see [Configuring time tracking](https://confluence.atlassian.com/x/qoXKM).  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param headers Optional headers to include in the request
   * @return TimeTrackingConfiguration
   * @throws ApiException if fails to make API call
   */
  public TimeTrackingConfiguration getSharedTimeTrackingConfiguration(Map<String, String> headers) throws ApiException {
    ApiResponse<TimeTrackingConfiguration> localVarResponse = getSharedTimeTrackingConfigurationWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * Get time tracking settings
   * Returns the time tracking settings. This includes settings such as the time format, default time unit, and others. For more information, see [Configuring time tracking](https://confluence.atlassian.com/x/qoXKM).  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @return ApiResponse&lt;TimeTrackingConfiguration&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TimeTrackingConfiguration> getSharedTimeTrackingConfigurationWithHttpInfo() throws ApiException {
    return getSharedTimeTrackingConfigurationWithHttpInfo(null);
  }

  /**
   * Get time tracking settings
   * Returns the time tracking settings. This includes settings such as the time format, default time unit, and others. For more information, see [Configuring time tracking](https://confluence.atlassian.com/x/qoXKM).  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;TimeTrackingConfiguration&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TimeTrackingConfiguration> getSharedTimeTrackingConfigurationWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getSharedTimeTrackingConfigurationRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getSharedTimeTrackingConfiguration", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<TimeTrackingConfiguration>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        TimeTrackingConfiguration responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<TimeTrackingConfiguration>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<TimeTrackingConfiguration>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getSharedTimeTrackingConfigurationRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/rest/api/3/configuration/timetracking/options";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Select time tracking provider
   * Selects a time tracking provider.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param timeTrackingProvider  (required)
   * @return Object
   * @throws ApiException if fails to make API call
   */
  public Object selectTimeTrackingImplementation(@javax.annotation.Nonnull TimeTrackingProvider timeTrackingProvider) throws ApiException {
    return selectTimeTrackingImplementation(timeTrackingProvider, null);
  }

  /**
   * Select time tracking provider
   * Selects a time tracking provider.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param timeTrackingProvider  (required)
   * @param headers Optional headers to include in the request
   * @return Object
   * @throws ApiException if fails to make API call
   */
  public Object selectTimeTrackingImplementation(@javax.annotation.Nonnull TimeTrackingProvider timeTrackingProvider, Map<String, String> headers) throws ApiException {
    ApiResponse<Object> localVarResponse = selectTimeTrackingImplementationWithHttpInfo(timeTrackingProvider, headers);
    return localVarResponse.getData();
  }

  /**
   * Select time tracking provider
   * Selects a time tracking provider.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param timeTrackingProvider  (required)
   * @return ApiResponse&lt;Object&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Object> selectTimeTrackingImplementationWithHttpInfo(@javax.annotation.Nonnull TimeTrackingProvider timeTrackingProvider) throws ApiException {
    return selectTimeTrackingImplementationWithHttpInfo(timeTrackingProvider, null);
  }

  /**
   * Select time tracking provider
   * Selects a time tracking provider.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param timeTrackingProvider  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Object&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Object> selectTimeTrackingImplementationWithHttpInfo(@javax.annotation.Nonnull TimeTrackingProvider timeTrackingProvider, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = selectTimeTrackingImplementationRequestBuilder(timeTrackingProvider, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("selectTimeTrackingImplementation", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<Object>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        Object responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Object>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<Object>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder selectTimeTrackingImplementationRequestBuilder(@javax.annotation.Nonnull TimeTrackingProvider timeTrackingProvider, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'timeTrackingProvider' is set
    if (timeTrackingProvider == null) {
      throw new ApiException(400, "Missing the required parameter 'timeTrackingProvider' when calling selectTimeTrackingImplementation");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/rest/api/3/configuration/timetracking";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(timeTrackingProvider);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Set time tracking settings
   * Sets the time tracking settings.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param timeTrackingConfiguration  (required)
   * @return TimeTrackingConfiguration
   * @throws ApiException if fails to make API call
   */
  public TimeTrackingConfiguration setSharedTimeTrackingConfiguration(@javax.annotation.Nonnull TimeTrackingConfiguration timeTrackingConfiguration) throws ApiException {
    return setSharedTimeTrackingConfiguration(timeTrackingConfiguration, null);
  }

  /**
   * Set time tracking settings
   * Sets the time tracking settings.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param timeTrackingConfiguration  (required)
   * @param headers Optional headers to include in the request
   * @return TimeTrackingConfiguration
   * @throws ApiException if fails to make API call
   */
  public TimeTrackingConfiguration setSharedTimeTrackingConfiguration(@javax.annotation.Nonnull TimeTrackingConfiguration timeTrackingConfiguration, Map<String, String> headers) throws ApiException {
    ApiResponse<TimeTrackingConfiguration> localVarResponse = setSharedTimeTrackingConfigurationWithHttpInfo(timeTrackingConfiguration, headers);
    return localVarResponse.getData();
  }

  /**
   * Set time tracking settings
   * Sets the time tracking settings.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param timeTrackingConfiguration  (required)
   * @return ApiResponse&lt;TimeTrackingConfiguration&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TimeTrackingConfiguration> setSharedTimeTrackingConfigurationWithHttpInfo(@javax.annotation.Nonnull TimeTrackingConfiguration timeTrackingConfiguration) throws ApiException {
    return setSharedTimeTrackingConfigurationWithHttpInfo(timeTrackingConfiguration, null);
  }

  /**
   * Set time tracking settings
   * Sets the time tracking settings.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
   * @param timeTrackingConfiguration  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;TimeTrackingConfiguration&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TimeTrackingConfiguration> setSharedTimeTrackingConfigurationWithHttpInfo(@javax.annotation.Nonnull TimeTrackingConfiguration timeTrackingConfiguration, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = setSharedTimeTrackingConfigurationRequestBuilder(timeTrackingConfiguration, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("setSharedTimeTrackingConfiguration", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<TimeTrackingConfiguration>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        TimeTrackingConfiguration responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<TimeTrackingConfiguration>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<TimeTrackingConfiguration>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder setSharedTimeTrackingConfigurationRequestBuilder(@javax.annotation.Nonnull TimeTrackingConfiguration timeTrackingConfiguration, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'timeTrackingConfiguration' is set
    if (timeTrackingConfiguration == null) {
      throw new ApiException(400, "Missing the required parameter 'timeTrackingConfiguration' when calling setSharedTimeTrackingConfiguration");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/rest/api/3/configuration/timetracking/options";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(timeTrackingConfiguration);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
